### ISSUE TITLE
[BUG]: Trait min and max settings don't import from breedbase via brapi

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#1000]
### Description

Trait in Breedbase:
![image](https://github.com/user-attachments/assets/9b8ccf7f-183c-4bf9-b51a-d80ccd3b0fc9)

Once imported into Fieldbook:
![20240712_161541_3298193622274581063](https://github.com/user-attachments/assets/8d67cc72-39df-44b7-bebf-4ed754af9ca3)

**Comment by trife** [comment]
Related to #888

**Comment by chris263** [comment]
@trife Is there any chance to escalate this issue to high priority? It’s becoming critical for corn data collection starting in December in South America.

**Comment by trife** [comment]
@chaneylc Can look into it next week.
