### ISSUE TITLE
[BUG]: Move to Unique identifier doesn't work for certain strings

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#1001]
### Description

When I import a trial with the primary id as ObservationUnitName, which are long strings, and scan barcodes encoding the  string I get the error "no matching entry'". When I import the primary id as ObservationUnitDbId, which are totally numeric, and scan  the barcode with the DbId it works without error. 

Example of a an ObservationUnitName that doesn't work: 24TET-162KA0290-14
Example of the corresponding DbID that does work: 59466

**Comment by trife** [comment]
Search scanning only searches through the unique ID (from brapi that's the OUDbId) but not the name since this has no unique requirement. We have plans to allow users to select other columns to use as the search materials in v6 (#792)

**Comment by ch728** [comment]
oh, okay, I will just use the OUBbld  then. Thanks for the info!
