### ISSUE TITLE
[BUG]: Keypad is not responding

### ISSUE THREAD

**Issue by To-Chia** [PhenoApps/Field-Book#1037]
### Description

The keypad for entering trait values is not responding. NA could not be entered either. But I could still add traits. The keypad of the tablet may still be normal.

### Field Book version

5.5.24

**Comment by chaneylc** [comment]
Hello @To-Chia is it possible your data is locked? You may have a "lock" icon in the top right toolbar, if it shows locked then the user can't enter data.

**Comment by To-Chia** [comment]
Thank you @chaneylc. I didn't notice that. After I unlocked it, I can enter data again. Thank you!
