### ISSUE TITLE
[BUG]: User guide is not available

### ISSUE THREAD

**Issue by kadreher** [PhenoApps/Field-Book#1044]
### Description

Greetings.
We noticed that the user guides are not available (impossible to get access to Documentation/Manual). Even from the app if you go to "about" then manual... the url does not work (https://docs.fieldbook.phenoapps.org/en/latest/fields.html)
Could you please help to provide access to the user guide again?

### Field Book version

5.6.23

**Comment by trife** [comment]
Hi @kadreher - we're working on migrating to a new docs platform for v6 and I deleted the DNS record a little too early. You can access the current docs here: https://field-book.readthedocs.io/en/latest/

I'll leave this open until the new docs are live.

**Comment by kadreher** [comment]
Hi @trife,

Thank you very much!
