### ISSUE TITLE
[BUG]: Field trial name imported as UUID instead of human readable name

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#1046]
### Description

When importing  a field with a .xls file named something like "24tetsu" the name is displayed as shown below.
![1000001821](https://github.com/user-attachments/assets/d5e4f48a-a358-4a06-9882-8b68157ad141).

I have tested fields with different names and this happens every time. This is using Lenovo Tab M8 and M9 tablets with FieldBook version 5.6.23.

### Expected behavior

Name of field upload file should be the display name for the field.

### Field Book version

5.6.23

**Comment by trife** [comment]
That's really weird... I'm not seeing the same behavior on a Pixel or the M9 I just tested. Does this happen for xlsx or csv files? Can you post/send one of the files this is happening for?

**Comment by ch728** [comment]
I tested if further and I realized it only happens when I import the file from Onedrive. If I download the file from Onedrive and then import it from the local file it works as expected. File attached.

[24WrtPu_plants.xls](https://github.com/user-attachments/files/16993890/24WrtPu_plants.xls)
