### ISSUE TITLE
[BUG]: Issues with GoPro Trait

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#1054]
### Description

When moving from plot to plot the gopro sporadically drops connection. The connect symbol button will appear instead of the photoshoot screen. After the connection is dropped it is very difficult to re-establish the connection.The app will say it connected successfully and when I advance to the next plot I can see the gopro screen flicker as if transitioning for the next photo, but I still only see the connect button and not the photoshoot screen. Often I will have to restart the tablet and the gopro to re-establish a connection. Even then it doesn't always work. Sometimes it just takes letting the tablet sit for 30 minutes and trying again. I can't figure out what the magic is to getting the connection to work. 

The other issue is lag and photo loss.  It takes 30-40 seconds to load a photo. Usually I can keep taking photos and the photos will eventually load, but sometimes the photo is "lost" and I end up with a perpetual spinning loop icon. It never leaves and if you try to delete a failed photo the app crashes. 

I am using the latest version of the app (updated yesterday), Lenovo M9 tablet, and GoPro 11.  Issue seems slightly worse when using outdoors vs. indoors in a photo booth setup.

**Comment by trife** [comment]
@ch728 I think there are some improvements for this in the v6 code based. I'll follow up once v6 is built and can be tested on your end.

**Comment by ch728** [comment]
Sounds good, thanks! The GoPro trait is very versatile and I look forward to using it heavily in the future.
