### ISSUE TITLE
[REQUEST]: Date Traits - ability to assign format for individual date traits instead of a global setting

### ISSUE THREAD

**Issue by hkmanching** [PhenoApps/Field-Book#1057]
### Description

Some date traits are recorded as the actual date (YYYY-MM-DD) said trait is observed, while others would be better suited for day of year recording like those used in "days to" or "days from" calculation. Currently, you can change the global setting for date format, limiting the date traits to a single type. It would be useful to be able to assign format to individual date traits so you can record both types efficiently.

**Comment by trife** [comment]
Duplicate of #896
