### ISSUE TITLE
[BUG]: Barcode should be configurable for observationunit_name, not only DbId, when BrAPI is used

### ISSUE THREAD

**Issue by lukasmueller** [PhenoApps/Field-Book#1062]
### Description

Currently when importing with BrAPI, fieldbook will only match barcode with DbIds, not the name. With Breedbase, people have traditionally used the observation unit name for the barcode

### Expected behavior

allow barcode to contain the name and search it in the fieldbook

**Comment by trife** [comment]
Duplicate of #792
