### ISSUE TITLE
[BUG]: Enabling high contrast mode on new e-ink Palma install does not work

### ISSUE THREAD

**Issue by hkmanching** [PhenoApps/Field-Book#1063]
### Description

After installing fieldbook on Palma device, the app detects the device is e-ink and asks if the user wants to enable high contrast mode. When the user selects "ok", high contrast mode is not enabled automatically.

**Comment by trife** [comment]
Looks like it also prompts the user to switch the second time it's opened and that time it works. We're moving this prompt to an intro screen in v6 so will retest this then to see if it's still an issue.

**Comment by chaneylc** [comment]
Looks like this is no longer an issue on version 6. Feel free to reopen this if the issue continues.
