### ISSUE TITLE
[BUG]: Ordinal scale displaying numbers but not categories 

### ISSUE THREAD

**Issue by PepperHouse** [PhenoApps/Field-Book#1088]
### Description

- When working with ordinal traits (e.g., 1=very low; 2=low; 3=medium; 4=high; 5=very high), only the numbers are displayed on the screen and the word "_null..._" appears under the trait name.

<img width="372" alt="image-20240729-181442" src="https://github.com/user-attachments/assets/5ea23097-84cd-4130-929b-00a94762e957">

- Pressing the screen on “_null..._” reveals the categories, but the functionality is hidden and there is no indication that the “_null_” text is clickable.  Note that the list of categories displays twice.**

<img width="381" alt="image-20240729-181654" src="https://github.com/user-attachments/assets/224f9395-d6d1-442f-a30e-f3dcad878a50">

### Expected behavior

- Ability to toggle between numbers and categories
- List of categories should appear once.

### Field Book version

5.6.25

**Comment by trife** [comment]
Was this trait imported via BrAPI? Can you go to `Settings > BrAPI` and toggle the Value vs Label display and see if it fixes your issue?

**Comment by PepperHouse** [comment]
Yes.  The trait was imported via BrAPI.  I changed the settings from Values to Label display and now I see the categories (instead of numbers).  Thank you.    **NOTE:**  The word _null_ and the duplicated list of categories still persist.

**Comment by trife** [comment]
The categories are definitely and `null` is probably an issue with the information being supplied by the host database.
