### ISSUE TITLE
missing data on export csv in database format

### ISSUE THREAD

**Issue by marcusmchale** [PhenoApps/Field-Book#11]
Some entries are missing when I export a fieldbook database to csv in database format.  They are there in the database and turn up when I export in table format but I need the metadata from these entries.

[fieldbook-csv.zip](https://github.com/PhenoApps/Field-Book/files/1450178/fieldbook-csv.zip)

Attaching the db files as well

[fieldbook-db.zip](https://github.com/PhenoApps/Field-Book/files/1450125/fieldbook-db.zip)

I tried this on another device (re-created the database by entering data through the app, not by import) and had the same issue: attaching this data too.

[example2.zip](https://github.com/PhenoApps/Field-Book/files/1450262/example2.zip)

also adding the fields.csv and traits.trt files that I used to set these up in case the issue is related to these:

[fields_traits.zip](https://github.com/PhenoApps/Field-Book/files/1450458/fields_traits.zip)

edit: the traits file in the above zip had a trait with 13 categories which is over the limit mentioned in the manual so I dropped the last of these from the traits.trt file and repeated the above with the same issue occurring. On this run I also replaced the fields.csv file with one one where all fields were completed (not just the uid). Attaching these files too just in case you want to test, it may make more sense to use these ones: 

[updated-fields_traits.zip](https://github.com/PhenoApps/Field-Book/files/1450612/updated-fields_traits.zip)

**Comment by trife** [comment]
Hi Marcus, looking into this. Will post updates when I figure out what the issue is.

**Comment by trife** [comment]
Until I get this figured out, here's all of your data in database format.
[field-book-csv-db-export.zip](https://github.com/PhenoApps/Field-Book/files/1455516/field-book-csv-db-export.zip)

**Comment by marcusmchale** [comment]
No bother, it is all test data anyway but thanks for looking into it.

I am developing a web service and database for an EU funded project (BreedCAFS)[](https://github.com/marcusmchale/breedcafs) and we are planning on using Field Book for field data collection. I only noticed this bug in preparing a presentation for today and I guess it is something easy to fix that was introduced when you transitioned to private CSVWriter functions.

**Comment by marcusmchale** [comment]
I have now looked at the database in a SQLite database and noticed that the values that aren't exported had somehow had their "trait" in user_traits table changed to text (from multticat or location). I am trying to work out how this happens in the app now.

**Comment by marcusmchale** [comment]
The below is an example of the log (debugging in android studio) when this happens. Firstly reset database and load default data. Deselect all but height, location and notes in the traits. Navigate to location (without passing notes) and set the location. When you navigate to notes and back to location, the location is set to text type.

12-19 10:02:10.678 13668-13668/com.fieldbook.tracker E/Field Book: For input string: "0.0; 0.0"
12-19 10:02:10.678 13668-13668/com.fieldbook.tracker W/location: 0.0; 0.0
12-19 10:02:10.687 13668-13668/com.fieldbook.tracker W/location: 0.0; 0.0
12-19 10:02:13.090 13668-13668/com.fieldbook.tracker E/Field Book: empty String
12-19 10:02:13.418 13668-13668/com.fieldbook.tracker I/AssistStructure: Flattened final assist data: 16244 bytes, containing 1 windows, 76 views
12-19 10:02:18.881 13668-13668/com.fieldbook.tracker W/text: 0.0; 0.0

**Comment by marcusmchale** [comment]
I may have a fix, still testing though I changed the below in MainActivity.java at line ~532. It seems a hard-coded "text" type may be the issue.

                        //updateTrait(currentTrait.trait, "text", en.toString());
                        updateTrait(currentTrait.trait, currentTrait.format, en.toString());

**Comment by trife** [comment]
Thanks for the fix! I'll include it in the next release. Lt me know if the problem resurfaces.
