### ISSUE TITLE
[BUG]: Camera preview crash 6.0.1

### ISSUE THREAD

**Issue by ramierop** [PhenoApps/Field-Book#1120]
### Description

Using a S22, pressing the vol up/down button seems to crash the image preview. It seems to refresh and show the camera preview, and previous images collected, but not an image collected from pressing the vol up/down button. 

Image is collected by pressing the camera shutter button on the screen, but that can be hid by the number of infobars, as shown in screen recording.

https://github.com/user-attachments/assets/410fd792-f0b8-4d4f-806c-b1b00958beeb

Let me know if you would like more information from me. 

[2024-12-12-12-10-00_systemdb11.zip](https://github.com/user-attachments/files/18115160/2024-12-12-12-10-00_systemdb11.zip)

### Expected behavior

I would like for pressing the vol up/down button to take an photo while using the preview. 

### Field Book version

6.0.1

**Comment by ramierop** [comment]
@bellerbrock is there anything else we talked about on this one?

**Comment by trife** [comment]
@ramierop Volume buttons can't currently be used to take pictures. If you've enabled the media commands experimental option, it uses the play/pause commands to take pictures.
