### ISSUE TITLE
[BUG] Cannot import a new field from BrAPI if there’s already previously imported field

### ISSUE THREAD

**Issue by abatac** [PhenoApps/Field-Book#126]
**Describe the bug**
Cannot add/import a new field from BrAPI if there’s already a previously imported field. An error message “Unique identifier column contains duplicates or has already been used in a different file“ is displayed.

**To Reproduce**
1. Authorize BrAPI
2. In the Fields section, import a field from BrAPI
3. Select a field, click Save Field and click OK
4. Go back to the Fields section, import a new field from BrAPI
5. Select a different field, click Save Field and click OK
6. An error message “Unique identifier column contains duplicates or has already been used in a different file“ is displayed.

**Expected behavior**
A field should be imported it it does not yet exist in the app.

**Device Info (please complete the following information):**
 - Model: Android emulator
 - OS: Android 10
 - Field Book Version 4.2

**Additional context**

**Comment by abatac** [comment]
@BrapiCoordinatorSelby @mcrimi @nahuel-soldevilla

**Comment by trife** [comment]
@BrapiCoordinatorSelby @timparsons do you know if there was any reason that the `field.setUnique_id` was set to use `plot` instead of `observationUnitDbId` ? Just making sure I don't inadvertently break something. https://github.com/PhenoApps/Field-Book/commit/0b77e3e66b0b4b94fbc217961ccea3062b1db79d

**Comment by BrapiCoordinatorSelby** [comment]
I don't remember any specific reason behind this. Looks like it could have been a copy and paste from the very first iteration of the BrAPI code.

**Comment by trife** [comment]
Good enough for me!
