### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [PhenoApps/Field-Book#14]
Hi,

Since this app is GNU GPL 2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? It would be awesome for people like me that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/)

**Comment by trife** [comment]
I'll consider it with the next release. Thanks!

**Comment by trife** [comment]
Unfortunately with the addition of Crashlytics, submission to F-Droid and maintenance of multiple versions of the app is unworkable.
