### ISSUE TITLE
No reaction when clicking export

### ISSUE THREAD

**Issue by JIN-HY** [PhenoApps/Field-Book#140]
Hi, 

I am using fieldBook 4.3.0. When I click "export" to make csv files, nothing comes out. It just stays at the main content. Could anyone help me export or just see my data?

Thanks, 
Hongyu

**Comment by trife** [comment]
This was fixed in 4.3.1 and is available on Google Play. Alternatively to updating, you can set a default export method in the settings and export will work correctly.
