### ISSUE TITLE
[BUG] Crash on first file import after deleting database.

### ISSUE THREAD

**Issue by chaneylc** [PhenoApps/Field-Book#149]
**Describe the bug**
The following exception occurs after deleting the database and then importing a field sample file on the develop branch.

`2020-08-26 20:18:26.153 14931-18768/com.fieldbook.tracker E/SQLiteLog: (1) table android_metadata already exists
2020-08-26 20:18:26.153 14931-18768/com.fieldbook.tracker E/Field Book: table android_metadata already exists (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE android_metadata (locale TEXT)`

**To Reproduce**
1. Delete database through settings.
2. Import field_sample.csv

**Expected behavior**
Currently nothing imports, but if you try to import the same file again it will import correctly.

**Device Info (please complete the following information):**
Moto X Android 9

**Comment by trife** [comment]
Resolved in v4.5
