### ISSUE TITLE
Photo trait fails silently if there are forward slashes in unique identifier field

### ISSUE THREAD

**Issue by bellerbrock** [PhenoApps/Field-Book#15]
I encountered this when a user included the date in the unique id. Looks like it's because photos are saved using the unique identifier in the filename, and then the forward slashes in the name are interpreted as separating non-existent directories.

Ideally people just wouldn't use special characters in the unique id, but it happens. When they do, it would be helpful to warn users and/or fail to record a photo with an informative error if possible.

**Comment by trife** [comment]
Slashes won't be allowed in unique identifiers in the next version.
