### ISSUE TITLE
[BUG] BrAPI import Study 1 throws index out of bounds exception.

### ISSUE THREAD

**Issue by chaneylc** [PhenoApps/Field-Book#150]
**Describe the bug**
Following error occurs, application does not crash. This is applicable in master and develop branches.
2020-08-27 16:32:55.412 26615-26615/com.fieldbook.tracker E/error: java.lang.IndexOutOfBoundsException: Index: 9, Size: 8

**To Reproduce**
1. Go to fields activity
2. import via brapi
3. choose study 1 and press save field and ok

**Expected behavior**
A study should be loaded, especially since the dialog shows plots found.

**Screenshots**
![image](https://user-images.githubusercontent.com/5421632/91497659-f65ef700-e883-11ea-9655-d5197e628159.png)

**Device Info (please complete the following information):**
 - Pixel 2 AVD Android 9

**Comment by trife** [comment]
@BrapiCoordinatorSelby any idea what's causing this?

**Comment by BrapiCoordinatorSelby** [comment]
Someone must have been playing around and pushed some bad data up into the server. There were a couple new plots with no x,y position data and the app didn't know what to do with it. I redeployed the test server so everything should be working now. I'll dig in a little to see if the app code can be a little more robust to this kind of issue, or at least catch it and tell the user specifically.
