### ISSUE TITLE
[BUG] Crash when trying to save photos

### ISSUE THREAD

**Issue by segraha3** [PhenoApps/Field-Book#153]
**Describe the bug**
After taking an image in the field and pressing save the error "Unfortunately, Field Book has stopped." occurs. When the error is dismissed Field Book is still open. Other traits in use are collecting and saving data fine (boolean and numeric).

**To Reproduce**
1. Select a field
2. Select a trait of type photo
3. Go to Collect
4. Click on the camera icon
5. Take photo
6. Press "Save"
7. See error: "Unfortunately, Field Book has stopped."

**Expected behavior**
Photo should save and return to data collection page. 

**Device Info (please complete the following information):**
 - Model: Samsung Galaxy Tab 4
 - OS: Android 5.1.1
 - Field Book Version 4.4.0

**Comment by trife** [comment]
This should be fixed in v4.1.1 which was released Sept 7.

**Comment by segraha3** [comment]
Thanks! Not sure how I missed the update but it is much appreciated!
