### ISSUE TITLE
[BUG] data lost after collecting data

### ISSUE THREAD

**Issue by matticulinaris** [PhenoApps/Field-Book#154]
Hi there,
I'm new to GitHub and just came here to ask for some help with field book app.
I'm using field book for some weeks now and I really like it!
Now I got a real problem: after almost two days of collecting data in the field I wanted to export these data as a .csv-table via bluetooth from my smartphone to my laptop. I did data export this way several times before and it worked great. But now theres no data in the .csv-table and even no data in the field book app when I'm looking for the data in the "collect data-window".
As far as I know field book saves data immediately while collecting - am I right? I was asking myself if there is any possibility to get the data from a backup or something?

I'm using field book Version 4.1.4
and my phone is a Huawei Y5 2018 with Android 8.1.0

I'd be great if someone could help me!
Thanks...

Greetz from Germany,
Matti

**Comment by trife** [comment]
Resolved over email. Will reopen if the issue occurs again.
