### ISSUE TITLE
[FEATURE] BrAPI pagination to all BrAPI screens

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#159]
As discussed in https://github.com/PhenoApps/Field-Book/pull/152

**Comment by BrapiCoordinatorSelby** [comment]
@trife are you working on this? 
I had some time last week so I started poking at it before I realized you opened this issue. I've got something roughly working but not finished yet.

**Comment by trife** [comment]
I haven't made any progress on this so I would be happy to accept your contributions when they're completed!
