### ISSUE TITLE
[BUG] Improve/Fix Print trait layout

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#174]
Long column names, general improvement

**Comment by bellerbrock** [comment]
Not sure if this merits a separate issue or not, but Russell has pointed out that the pressing the print icon prompts to re-select the bluetooth connection with each new field entry. Having the connection/selection persist between entries would save a lot of clicking.

**Comment by bellerbrock** [comment]
Notes from meeting:
- Handle UI edge cases like long column names from field imports
- Fix for repeated connection prompts
