### ISSUE TITLE
Modify Fields page and workflow

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#178]
- [x] Add beta setting to use new fields workflow

### Fields list

- [x] #805
- [x] #775
- [x] Most recently edited or imported file is pinned to the top of list
- [x] Long press (or press icon) to enter selector mode that allows multiple list items to be selected
- [x] Selector mode should have specific actions on toolbar: delete, export, archive
- [x] #267
- [x] When in selector mode, add a select all button to the toolbar (double checks)
- [x] Move add field button to FAB
- [x] Add "new field" item to add field dialog and remove from toolbar
- [x] Sort field list by import source, **import date**, edit date, export date, or **name**.
- [x] highlight current sort option and add reset
- [x] add shaded circle to show % complete for trait detail sections
- [x] include icons in add field option list and move create new to end

### Per field activity

- [x] Move existing information to per field activity
- [x] Toolbar labeled 'Field Detail' with rename, sort, and delete actions
- [x] Collapsible design card that shows field details - name+import date and source, entry number and sort order, last collected by person
- [x] Click action cards for collect with last edit date, Export with last export date, Sync (if brapi) with last sync date
- [x] Trait card with num traits, num observations, and recyclerview items for each collected traits with type icon, observation count
- [x] Format dates to be semantic (i.e. Today, Yesterday, Never, Last year, Mon DD)
- [x] Ignore data from deleted traits
- [x] Add trait statistics graphs - histograms for numeric data
- [x]  Add trait statistics graphs - bar charts for ordinal/categorical data
- [x] https://github.com/PhenoApps/Field-Book/issues/960

**Comment by bellerbrock** [comment]
mockups: 
![Screenshot from 2023-11-29 15-13-07](https://github.com/PhenoApps/Field-Book/assets/11297346/ba0560b3-2331-40a3-80bf-9fb438c33b46)
![Screenshot from 2023-11-29 15-14-01](https://github.com/PhenoApps/Field-Book/assets/11297346/e86e1f47-9b99-4813-9bb7-248ae9f8109b)

**Comment by bellerbrock** [comment]
discussed today:
add archive/unarchive button to field detail page

low priority - add automated check for brapi trials to see if out of sync

**Comment by bellerbrock** [comment]
Note - test brapi export of multiple brapi trials at once.

**Comment by bellerbrock** [comment]
- [ ] Remove all ID info (secondary and primary will go away soon. Include original name. Join bullet points into a narrative.
- [ ] Add bold style to variables (filename, counts, sort factor, etc)
- [ ] Collect, export, sync icons to left, use right chevron icon on right
- [ ] Change Edit field Name to Edit Field. Will include name, location, barcode search column
- [ ] Change edit to edit alias, and display alias where name is currently displayed. Disallow editing of Brapi field aliases
