### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by ClayBirkett** [PhenoApps/Field-Book#179]
Can you add these to community servers under BrAPI

https://wheat-sandbox.triticeaetoolbox.org/
https://barley-sandbox.triticeaetoolbox.org/
https://oat-sandbox.triticeaetoolbox.org/

**Comment by trife** [comment]
@ClayBirkett did you close this because you'd rather not have the servers in the BrAPI section?

**Comment by ClayBirkett** [comment]
I realized that users will need more instructions about how to use the Field Book app with T3. They need to know that the information on our sandbox machines is removed each week. So, after they design experiment and upload field data that data also must be submitted to production machine.

I also thought I would have to re-enter the URL for BrAPI each time, but that does not appear to be the case.

I created an instruction sheet https://wheat.triticeaetoolbox.org/static_content/files/FieldBookAppT3.pdf

Yes, we would still like our machines listed in the community servers list.
using Field Book App with T3 - wheat.triticeaetoolbox.org<https://wheat.triticeaetoolbox.org/static_content/files/FieldBookAppT3.pdf>
4. Import Field from using BrAPI 1) go to Fields 2) select "+" icon in upper right corner 3) select "BrAPI" 4) select trials from database server
wheat.triticeaetoolbox.org

________________________________

**Comment by trife** [comment]
Going to leave this open so I don't forget to add the servers.
