### ISSUE TITLE
[BUG] Brapi authentication issue

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#180]
Authentication doesn't seem to work properly when there is ngnix password set up. Please see https://github.com/solgenomics/sgn/issues/3117 for context.

**Comment by trife** [comment]
@BrapiCoordinatorSelby do you have any ideas about this?

**Comment by BrapiCoordinatorSelby** [comment]
solgenomics/sgn#3117 has a few different things going on.
Basically, yea, it won't work properly with the nginx password. They are two different types of authentication protocols, nginx is using basic credentials, Field Book is expecting OAuth2, and they are incompatible with each other. 

- Option 1: Field Book adds Basic auth as a way to authenticate. I don't recommend this because it gives Field Book access to the users credentials. Field Book would have to store these credentials, or make the user login every time they made a BrAPI call. Storing passwords is difficult to do correctly
- Option 2: Turn off the nginx password and rely on the Breedbase OAuth system for authentication, with the secure flag Nick mentioned to protect the APIs. The BrAPPs within Breedbase would need to be updated to use the login token (this should be a pretty trivial fix, but a Breedbase dev would need to speak to this)

@ch728 you mentioned a bug downloading plots in when the nginx password was off. I'm guessing that is an unrelated bug since Auth worked in otherplaces. if you can make me a user on your system, I can try to replicate it with the Field Book logs in Android studio.

**Comment by BrapiCoordinatorSelby** [comment]
@nickmorales 

> isn't option 1 a better approach?

No

>is that a standard practice in brapi?

Yup Breedbase should be expecting _and verifying_ an access token with every request. This is the OAuth2 standard, and BrAPI adopted OAuth2 as best practice. Every BrAPI request documentation has a header "Authorization" and the value of that header should be the access token. Typically its in the format "Authorization":"Bearer <access_token>".

The main purpose is to allow access to data without giving the client (Field Book) access to the raw user credentials. The user logs into Breedbase using the standard, well tested, and well protected Breedbase login page. When they login, they exchange their user credentials for a token. The token has no secret information in it, but can be used as proof of user identity until it expires or is voluntarily invalidated. 

In option 1, Field Book is forced to handle user credentials. This is a tool outside of Breedbase control and should not be trusted. @trife could turn evil one day to add some code to start collecting usernames and passwords (extreme example but who knows, he is pretty shifty :P ). 

I made a page about OAuth2 basics on the BrAPI wiki a while ago. There are many other resources available online, I just tried to condense things down to the important topics. 
Specifically what we are talking about here is the Implicit Grant flow. The diagrams are done from the perpective of a web page, it would look a little different for an app, but its basically the same flow.
https://wiki.brapi.org/index.php/Authentication#Implicit_Grant

**Comment by nickmorales** [comment]
@BrapiCoordinatorSelby ok i see. It is currently implemented in breedbase to accept the Authorization: Bearer <access_token> header and it can take 'access_token'=token in the data parameters.
@ch728 We will need to make sure the breedbase internal use of brapps follows that too

**Comment by ch728** [comment]
Okay, so I have configured ngnix to not require password authentication for /brapi calls and have enabled the brapi secure login feature in breedbase. This seems to work except for the problems it causes with the embedded brapps in breedbase, which can hopefully be fixed at some point. 

Still having the issues with downloading the plots though. @BrapiCoordinatorSelby , I will see about setting up  temporary access so you can have a look.

**Comment by MFlores2021** [comment]
@ch728 I'll try to replicate the issues with the brapps. Which brapp did you try?

**Comment by ch728** [comment]
@MFlores2021  I have tried the pedigree viewer on the accession page. The pedigree never loads when the brapi_require_login key is set to 1 but works when it set to 0.

**Comment by BrapiCoordinatorSelby** [comment]
I worked with @ch728 and the downloading plots issue seems to be a timeout problem. Field Book is set to timeout if a request takes longer than 60sec. Unfortunately, Breedbase can take a really long time to come back with results. 

I recreated the BrAPI query against CassavaBase and it took 8 minutes to return 42 plots from a single trial. We can increase the timeout on the FieldBook side, but 8 minutes seems like a _really_ long time for that size trial. The trial I picked did have observations attached, but it was still only about 1000 data points total. In my opinion, something in Breedbase is not optimized correctly.

https://cassavabase.org/brapi/v1/studies/3637/observationunits?page=0&pageSize=1000&observationLevel=plot

![postman_long_request](https://user-images.githubusercontent.com/32845555/97628503-2bfa9a80-1a03-11eb-889a-9c5a2c794375.png)

**Comment by trife** [comment]
We could definitely add a user-configurable timeout value, but I agree with @BrapiCoordinatorSelby that 8m for 42 plots sounds like there are larger areas that need to be optimized.

**Comment by MFlores2021** [comment]
Better to use V2, speed has been improved for that call https://cassavabase.org/brapi/v2/observationunits?studyDbId=3637

**Comment by BrapiCoordinatorSelby** [comment]
@MFlores2021 Thanks! 
hahaha "improved speed" is an understatement, it went from 8 minutes down to 1 second!
I'll see what I can do to bump up the priority of Field Book BrAPI V2 compliance.

**Comment by trife** [comment]
@MFlores2021 @BrapiCoordinatorSelby 
It looks like v1 and v2 return different objects for the above call. How would a v2 call be structured to return the same object as v1?

**Comment by BrapiCoordinatorSelby** [comment]
@trife 
Both calls return `ObservationUnits`. The structure has changed a little from V1 to V2, but the information is the same. 
We will need the V2 java library that the BI team has started, then Field Book will need a new set of mapping functions to map the data from BrAPI V2 format to Field Book format.
Assuming that you want to support both V1 and V2 servers (no reason not to), then Field Book will also need to know which library, and by extension which mapping functions, to use when it makes a call. This could be detected automatically by the `/v2` in the base URL, or a user setting.
Supporting V2 is not a trivial enhancement, but we knew it was coming eventually.

**Comment by trife** [comment]
closing since the discussion has been resolved
