### ISSUE TITLE
[BUG] BrAPI export not working

### ISSUE THREAD

**Issue by ClayBirkett** [PhenoApps/Field-Book#182]
After collecting data the Export Data Local works but the Export Data BrAPI shows a screen that says 0 Observations and 22 Skipped Observations. The error message is "Nothing to sync"

![Screenshot_2020-10-30-12-17-34-440](https://user-images.githubusercontent.com/14339444/97730435-3754d100-1aaa-11eb-8fbe-d85bf0066368.jpeg)

 - Model: Lenovo M8
 - OS: Android 9
 - Field Book Version 4.5

Export Data Local
[2020-10-30-11-50-03_ClayTest1_database.txt](https://github.com/PhenoApps/Field-Book/files/5466291/2020-10-30-11-50-03_ClayTest1_database.txt)

**Comment by trife** [comment]
@ClayBirkett have you tested this with other fields/studies top see if you get the same behavior? @ctucker3 will probably be better-able to debug the underlying issue here then I am.

**Comment by ctucker3** [comment]
> @ClayBirkett have you tested this with other fields/studies top see if you get the same behavior? @ctucker3 will probably be better-able to debug the underlying issue here then I am.

Did you import the field and traits from brapi? It's been a while, but I think I recall that if you don't import those from brapi, you can't push them back to brapi because there is no id to send back. @nickpalladino might have a better idea, I think he has been somewhat working with fieldbook recently.

**Comment by nickpalladino** [comment]
@ctucker3 ya that's what it looks like given it's under the skipped traits for user created. One thing I noticed recently for BrAPI export is that I could export and it would say it was successful but the synced traits number would not update. So it seems there's been some kind of regression there but I haven't looked at the code. Have you seen this @trife?

**Comment by trife** [comment]
We haven't had reports of that from any users. We've been looking at extending some of our Firebase analytics to track events like this and could include that in our next update to see if it's happening in the released version.

**Comment by ClayBirkett** [comment]
I tried designing some more trials but I wasn't able to import them into Field Book. On one trial the app gets stuck and never finished import on another the app crashes. So it a step backwards, I'll have to debug our server BrAPI. Are there any issues with valid accessions names or will it accept anything?

Clay
________________________________

**Comment by ctucker3** [comment]
One thing I can thing of to try out is that the queries aren't timing out. I remember the brapi queries taking a while when we were integrating fieldbook with breedbase a while back. So if you have a lot of data in breedbase, maybe that is causing the issue? Here are the endpoints that brapi uses if you wanted to try them out outside of fieldbook:

/studies-search?pageSize=20&page=0
/studies/{studyId}
/studies/{studyDbId}/observationunits?observationLevel=plot&pageSize=1000&page=0
/studies/{studyDbId}/observationvariables?pageSize=200&page=0

**Comment by trife** [comment]
I think this is fixed but can be reopened if not.
