### ISSUE TITLE
[BUG] Can't use http:// brapi URL, only https://

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#223]
**Describe the bug**
Get an error trying to import studies for brapi v2 when using a http:// url.

```
java.net.UnknownServiceException: CLEARTEXT communication to localhost:7080 not permitted by network security policy
```

**To Reproduce**
1. Authorize brapi server with http:// url
2. Attempt to import studies from v2 server and get error

**Expected behavior**
List of studies is shown

**Device Info (please complete the following information):**
 - Model: [Pixel 3a API 30]
 - Field Book Version [brapi_v2]

**Comment by nickpalladino** [comment]
@BrapiCoordinatorSelby @trife @chaneylc Was this intentional or can I update the AndroidManifest.xml to allow cleartext communication?

**Comment by trife** [comment]
I'm not sure that this was intentional but I don't see any issue with changing it to allow cleartext.

**Comment by nickpalladino** [comment]
> I'm not sure that this was intentional but I don't see any issue with changing it to allow cleartext.

cool, thanks
