### ISSUE TITLE
Import sanitization to prevent SQL injection

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#229]
When imported headers contain ` or " the app crashes. Instead of trying to catch all of these ( `DataHelper.hasSpecialChars` ), they should just be imported correctly as plain text.

Related to #109 
Related to https://github.com/solgenomics/sgn/issues/3375

**Comment by chaneylc** [comment]
What branch is this and what method did you use for import? (brapi, local, database) Can you provide me with the 'generated file' that causes the crash?

**Comment by trife** [comment]
This is on develop. I just threw a quote and tick into the header of one of the sample files.
[field_sample_special.zip](https://github.com/PhenoApps/Field-Book/files/6172767/field_sample_special.zip)
