### ISSUE TITLE
[MINOR] issue with 4.5 version after authentication 

### ISSUE THREAD

**Issue by diegoguidotti** [PhenoApps/Field-Book#261]
We are testing BRAPI api v1 to synch with an existing web application.  In the master version (5.0) there is no problem (at least on the virtual device), in the current android app (4.5)  the app crash after switching back to the app after login.

The server redirects to the app calling:
location.href=fieldbook://?status=200&token=__xxxxxx__

Do we make any mistakes from our side?

**Comment by chaneylc** [comment]
I just tested authorization for a few different servers on 4.5 and wasn't able to reproduce the crash. If you want to send me temporary login credentials or a way to register for your server along with its address I can try to help figure out the issue. You can email me at chaneylc@gmail.com.

**Comment by diegoguidotti** [comment]
I have just tested again and it is working, probably was an issue in the server
