### ISSUE TITLE
[REQUEST] Different patterns for plot navigation

### ISSUE THREAD

**Issue by qmwnebrv** [PhenoApps/Field-Book#262]
Would it be possible to incorporate different patterns for advancing between plots and rows? For example, we typically collect data in a serpentine pattern, where we'd walk up a row, then walk down the next row (serpentine row x column). Other people I know collect data in a serpentine column x row pattern too. The only option in field book I can see is that you have to go to the start of a row each time you complete one..

**Comment by trife** [comment]
The current method for plot order in Field Book is entirely dependent on the order of plots in the imported file so it isn't only limited to sequential. We plan on adding in capacity for additional field sorting ( see #84 ) but haven't been able to prioritize this feature.
