### ISSUE TITLE
Date trait using calendar picker / Alternative layout for date trait

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#265]

**Comment by kadreher** [comment]
Hi @trife . We have a strong need from on of our user groups for the ability to select calendar dates in data capture (rather than using the +1/-1). Could you please let us know when this feature might be able to be implemented?

**Comment by trife** [comment]
@kadreher Our developer will likely be able to push out a quick fix this week. I'm trying to hire another developer but it's taking longer than expected.

**Comment by kadreher** [comment]
Hi @trife  - thank you! It would be great to receive this option so soon.

**Comment by trife** [comment]
Merged into 5.0.7 beta

**Comment by trife** [comment]
@chaneylc Two questions:
* Can we call the save button action when clicking OK in calendar selector dialog
* Is it possible to remember the last-selected date within the picker itself (maybe with a neutral "go to today" button to reset) and start the calendar from that previous date?

**Comment by chaneylc** [comment]
1. Yes that's possible.
2. Yes that's possible, but to be clear, you want the last picked date within the calendar saved as a preference, so that whenever a user uses the calendar it is initialized with the last chosen date (even if it's a different plot or study)?

**Comment by trife** [comment]
Yeah and add a neutral button that says "Today", deletes that prefKey, and moves the user to currentDate

**Comment by kadreher** [comment]
Thank you @trife and @chaneylc ! This is great!

**Comment by trife** [comment]
New behavior will be in 5.1 release!
