### ISSUE TITLE
[BUG] BrAPI study details import: ArrayIndexOutOfBoundsException when no X/Y information for *any* plot

### ISSUE THREAD

**Issue by nahuel-soldevilla** [PhenoApps/Field-Book#280]
**Describe the bug**
Exact same issue as #150 but in our case we don't have any x/y information for any plot, so the fix #155 won't work because the [Row and Col attributes are never mapped](https://github.com/PhenoApps/Field-Book/blob/8026d0bfc195c326801c845d3acd77c12dc67f3b/app/src/main/java/com/fieldbook/tracker/brapi/service/BrAPIServiceV1.java#L498).
We've experienced this issue just this week because before we were using some defaults for x and y (1, 1). Recently we removed those defaults, and we have studies that don't have any x/y information at all.
I'll just keep using those as a workaround.

**Expected behavior**
Not sure, assign some defaults and allow data collection? create a default grid? or make those values mandatory, providing a message?

**Screenshots**
out of bound in StudyDao.Companion#createFieldData:

![studydao-createfielddata](https://user-images.githubusercontent.com/19394293/125991301-f28437ba-93ff-4ca0-8b45-5962b2cf851c.png)

**Device Info (please complete the following information):**
 - Model: Android studio emulator Pixel 2
 - Field Book Version 5

**Comment by ctucker3** [comment]
@trife @chaneylc I am experiencing this issue too. What is the desired behavior? We might have to adjust our data depending on how you this is handled.

**Comment by trife** [comment]
@nahuel-soldevilla @ctucker3 Are you experiencing this using BrAPI v1.3 or v2?

**Comment by ctucker3** [comment]
Only with v1. I just tested v2 and it seems to work fine without positionCoordinateX and positionCoordinateY assigned.

**Comment by nahuel-soldevilla** [comment]
> Are you experiencing this using BrAPI v1.3 or v2?

I haven't really tested against v2, we still have some pending work in BMS to make it fully compliant with the v2 workflow.

**Comment by trife** [comment]
Looks like Row and Column were hard-coded as the Primary and Secondary order in v1. I think this was originally done to simplify the original implementation but @BrapiCoordinatorSelby can confirm.

The v2 service uses positionCoordinates with a fallback to the hard-coded values. I don't think it will take too much to implement the same approach in the v1. I might be able to work on this later in the week or @ctucker3 can include it as a part of his bugfix PR.

**Comment by ctucker3** [comment]
> I might be able to work on this later in the week or @ctucker3 can include it as a part of his bugfix PR.

I probably won't include it in my work this round. I'm trying to focus on v2 right now to get that working with our system.

**Comment by trife** [comment]
That's fine just trying to pawn off things to other people 😉. @chaneylc can probably get this fixed and align with your v2 fixes timeline.

**Comment by chaneylc** [comment]
The PR https://github.com/PhenoApps/Field-Book/pull/293 should fix this issue. I default the primary/secondary values for observation units to -1 when they don't have a coordinateX, coordinateY, (or X/Y in V1) field. @nahuel-soldevilla @ctucker3 is it normal to not allocate Row/Cols to your plots?

**Comment by ctucker3** [comment]
> is it normal to not allocate Row/Cols to your plots?

Not for us. If we are collecting data on plots in Field Book, we will always have rows and columns on them. There could be an exception on the future perhaps, but we don't have any exceptions now.

**Comment by nahuel-soldevilla** [comment]
> is it normal to not allocate Row/Cols to your plots?
I got some feedback from the team and there seems to be a lot of scenarios or experimental designs in BMS where this situation might happen, where it would be difficult to assign row/cols to the observation units.
