### ISSUE TITLE
[BUG] Delete observation no longer shows N/A value

### ISSUE THREAD

**Issue by ctucker3** [PhenoApps/Field-Book#290]
**Describe the bug**

I think it used to be the case that when you exported a brapi observation and then deleted it in the collection activity the value was set to "N/A" and a message was displayed telling you why that happened. 

This behavior is missing in v5.0 and v4.5 from what I can tell. 

I haven't looked back in versions to see where this was lost. 

**To Reproduce**
1. Import BrAPI studies and traits
2. Collect some data
3. Export that data via brapi
4. Go back to the collection screen
5. Delete one of your observations
6. The field will go blank and there will be no message

**Expected behavior**
N/A value is put into field and a warning message is displayed informing the user that brapi observations can't be deleted. Using N/A instead. 

**Screenshots**

**Device Info (please complete the following information):**
 - Model: Pixel 3a
 - OS: Android 10
 - Field Book Version v5.0 and v4.5

**Comment by trife** [comment]
Can observations that have been collected and exported via brapi be modified at all on the end server? I can see the purpose of writing N/A if it overwrites the previous observation or the user can then update the obsUnit/obsVar combination with a new observation, but if the N/A is entirely visual this should probably just be a toast or dialog instead.

**Comment by ctucker3** [comment]
Yep! When you edit an observation that has been synced, it will make a PUT call to the end server. I think we set it that way in the initial Field Book work since DELETE isn't an option in brapi. So, setting it to NA was the next best thing.
