### ISSUE TITLE
[BUG] CSV files cannot be attached to emails on some devices

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#308]
Implement fixes:
https://stackoverflow.com/questions/32318692/android-attaching-a-file-to-gmail-cant-attach-empty-file
https://stackoverflow.com/questions/62619201/android-intent-to-gmail-not-attaching-file-by-fileprovider-unable-to-attach-fil

**Comment by chaneylc** [comment]
Do you know what devices have this issue? So I can reproduce the problem.

**Comment by trife** [comment]
I asked the user who reported the issue and will let you know when I hear back.

**Comment by trife** [comment]
> CP3 Phones and Samsung tablets (GALAXY TAB A 8.0")

Not sure the Android version, though.

**Comment by trife** [comment]
Can't reproduce.
