### ISSUE TITLE
[REQUEST] Summary data selection

### ISSUE THREAD

**Issue by ramierop** [PhenoApps/Field-Book#317]
Request is not a problem, just a possible improvement.

What I am suggesting is to be able to select what is shown in the Summary icon. 
![Screenshot_summary](https://user-images.githubusercontent.com/70235332/128537689-86dff3b9-6e00-4323-9800-fc7162b810a5.png)

As a program we are trying to get more data driven and be able to make on the fly decisions using Fieldbook and Sweetpotatobase. In an attempt to be able to make those decisions from a single tablet we are downloading information from SPB, importing that dataset to Fieldbook, and making field ratings and selections. We download traits that are helpful for field selection and can see that information in the Summary icon. It can get very busy, and I'm not sure it needs all the information that is included with the imported dataset.

![Screenshot_standardview](https://user-images.githubusercontent.com/70235332/128537756-1a597ee2-9db5-4983-adf6-5f9d1e27dc4d.png)

**Describe the solution you'd like**
The ability to select what is seen in the Summary icon.

**Describe alternatives you've considered**
We can add more databars to the Collect screen, but after that I'm unable to display the traits that I want to collect. 
![Screenshot_infobars](https://user-images.githubusercontent.com/70235332/128537829-ab698009-5d9b-4584-9929-821a29ed48fe.png)

**Additional context**

**Comment by trife** [comment]
@ramierop This is a great idea. I don't have a timeline on getting it implemented, but will keep you updated via this issue.

**Comment by ramierop** [comment]
@trife Nice. Thanks for the update. Looking forward to see what y'all come up with.

**Comment by trife** [comment]
@ramierop This feature will be in v5.4 which will go into beta in December

**Comment by ramierop** [comment]
Hi Trevor,

Thanks for the update. I will be happy to check it out and see how it
works.

Hope you're doing well.

Russell
