### ISSUE TITLE
[BUG] BrapiExportActivity authentication

### ISSUE THREAD

**Issue by chaneylc** [PhenoApps/Field-Book#374]
**Describe the bug**
Export activity does not let you export observations if you don't have authentication, even if you use that activity's "Log In to Site" dialog and successfully authenticate.

**To Reproduce**
1. Import field
2. Make observations
3. Export activity with no authentication
4. Authenticate in the dialog

**Expected behavior**
When the dialog successfully authenticates it should persist.

**Comment by trife** [comment]
I think this is fixed. Closing for now but we can reopen if you're still seeing this.
