### ISSUE TITLE
[REQUEST] Add a way to filter BrAPI Trial fetch by year

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#393]
Currently all trials are loaded when importing using BrAPI. We have 100s of trials so this process is very slow. The user then has to scroll through a lot of trials to locate the trial they want to save to the phone. It would be useful to have the option to add year as a way of returning only relevant trials. It is straight forward for Breedbase because seasonDbId is year, so /brapi/v2/studies?seasonDbId=year can be used. Not sure if this is how it would be for other databases though...

**Comment by ch728** [comment]
Duplicate of https://github.com/PhenoApps/Field-Book/issues/172

**Comment by trife** [comment]
Hoping to include this in the release after 5.2. Chaney's also started some work on a search-based filtering feature and we may try to get both branches integrated into the same release.
