### ISSUE TITLE
Collect Data navigates to first plot, first trait after collect photo

### ISSUE THREAD

**Issue by ctucker3** [PhenoApps/Field-Book#41]
When the user collects a photo for the photo data type, it navigates the user back to the first plot, first trait in the field. Ideally, once the photo is collected, Field Book would resume on the trait and plot they had just collected data for.

**Comment by trife** [comment]
This is due to moveToSearch currently disabled but should work properly once it's fixed.

**Comment by ctucker3** [comment]
Would it be worth keeping this open as a reminder to test it once moveToSearch is added back in?

**Comment by trife** [comment]
Definitely will keep it open until it works properly again.

**Comment by trife** [comment]
https://github.com/PhenoApps/Field-Book/commit/ed6756c06c9a7ec5cc30dd8cb3e6801678bc0d47
