### ISSUE TITLE
Observations aren't deleted when trait is deleted

### ISSUE THREAD

**Issue by ctucker3** [PhenoApps/Field-Book#42]
If you import traits, collect data, and then delete one of the traits, its data will not appear in the data collection page. But, if you then create a trait with the same name as the one deleted, or import the same trait again, that observation value will reappear in the collect data page for the plot it was collected on, under the trait that was deleted and recreated.  

This is in conflict with the warning when a trait is deleted that associated data will be deleted. Bug is present in the master branch, and the google play version.

**Comment by ctucker3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIE-71 - Observations don't delete when trait is deleted](https://trello.com/c/FWoCNlh1/71-fie-71-observations-dont-delete-when-trait-is-deleted)

**Comment by trife** [comment]
We've implemented a sort of fix for this in #183 - observations aren't actually deleted but the link to them is severed. That way they are still recoverable but not easily accessible.
