### ISSUE TITLE
Select or import a field message displayed on Fields page

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#44]
Starting from a clean install you can go into the Fields page and return back to the main menu page by hitting the back button in the upper left. If you then go into the Fields page and load a field, either local or through brapi, then delete the field, you cannot go back to the main menu with the back button. Instead a message is displayed saying "Select or import a field."

It seems like this shouldn't be the case but if there's a particular reason for it, let me know.

**Comment by trife** [comment]
da9018a76822da39e73061220326a43fddfb3748
