### ISSUE TITLE
App crashing when selecting collect

### ISSUE THREAD

**Issue by barriball** [PhenoApps/Field-Book#473]
Version 5.2 
Device pixel 3a
App crashes when trying to collect new data.

**Comment by trife** [comment]
We're looking into this. Can you post or email the field file (or database export)?

**Comment by trife** [comment]
I think the upload for this failed and it just links back to the issue. Can you try uploading again?

**Comment by barriball** [comment]
[2022-07-21-12-34-40_systemdb9.zip](https://github.com/PhenoApps/Field-Book/files/9167889/2022-07-21-12-34-40_systemdb9.zip)

**Comment by trife** [comment]
I should be able to get the fix for this uploaded this afternoon.

**Comment by trife** [comment]
@barriball you can get the version with the fix from [here](https://github.com/PhenoApps/Field-Book/releases/download/524/Field-Book-v5.2.4.apk) or wait ~2h before it gets sent to your device.
