### ISSUE TITLE
Multiple images per trait

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#48]
@trife We're working on adding image export via the brapi /images endpoints. I see that you can have multiple images per image trait. It seems like ideally you'd want to have different image traits for different plant structures or whatever you are imaging. Maybe this is the intent, but I could see where it could be misused by having an image trait and then taking a bunch of pictures of different things and then lose the context for analysis. As far as I'm aware, the image trait is the only one where you can have multiple observations. Is your expectation that the functionality remain the same and all of the images for a plot are exported via brapi?

**Comment by trife** [comment]
The expectation would be that all images for a given plot would be exported via brapi. Images are the only trait right now where you can collect multiple observations, but we expect to extend this functionality to other traits to allow for derived traits, time series, and multiple measurements.

**Comment by nickpalladino** [comment]
Ok, sounds good
