### ISSUE TITLE
[BUG] No photo available was displayed in BMS when a new image is exported via BrAPI

### ISSUE THREAD

**Issue by lik-83** [PhenoApps/Field-Book#483]
**Describe the bug**
The "trait_photo_missing.png" is shown in BMS after the user export via BrAPI a new image.

**To Reproduce**
1. Log in to BMS
2. Create a study with observation with traits
3. Use Fieldbook app v5.2
4. Go to Fields section and import fields from the study via BrAPI
5. Go to Traits section, edit one trait datatype to photo.
6. Go to Collect section and select the trait with photo datatype.
7. Capture a photo.
8. Go to Export and export data via BrAPI
9. Check the image uploaded to the observation tab of the study in BMS
10.  A “No Photo Available” image is displayed in the preview and when it's downloaded and opened.

**Expected behavior**
Imported photo should display

**Screenshots**
![7cbad9db-8d65-4d53-91d3-053241c96698](https://user-images.githubusercontent.com/3207307/182881724-7939a5f7-23d0-4820-93e1-a6eb49e6243f.png)

**Device Info:**
 - Model: Pixel 2
 - OS: Android 28
 - Field Book Version: v5.2

**Comment by timparsons** [comment]
This was also observed when publishing to BreedBase

**Comment by chaneylc** [comment]
@timparsons can you check to see if this branch fixes the issue? 
hotfix/brapi_image_export/483
