### ISSUE TITLE
[BUG] Different page was displayed after authorizing while OAuth2 Implicit Grant was selected

### ISSUE THREAD

**Issue by lik-83** [PhenoApps/Field-Book#485]
**Describe the bug**
The user is always redirected to BRAPI Test Server ([auth.brapi.org](http://auth.brapi.org/)) when use 'OAuth2 Implicit Grant' as OIDC Flow.

**To Reproduce**
1. Go to Settings -> BrAPI 
2. Tap OIDC Flow and then select OAuth2 Implicit Grant.
3. Tap Base URL and enter a base url
4. Tap Save and Authorize

**Expected behavior**
User should see the login page set as the base URL

**Device Info (please complete the following information):**
 - Model: Pixel 2
 - OS: Android 28
 - Field Book Version: v5.2
 - 
**Additional context**
I guess the problem lies in this line: https://github.com/PhenoApps/Field-Book/blob/develop/app/src/main/java/com/fieldbook/tracker/activities/BrapiAuthActivity.java#L118.

**Comment by trife** [comment]
Fixed in develop and should ship with v5.3. Reopen if the issue reoccurs.
