### ISSUE TITLE
[BUG] Cloud imports using OneDrive not importing

### ISSUE THREAD

**Issue by rachelgreenh** [PhenoApps/Field-Book#500]
**Describe the bug**
When I opened the fieldbook app recently, I was required to Define a Storage Location. I have never previously been asked to define this before. I selected the folder called fieldBook that already existed on my device from when I installed the app. I usually add new fields from cloud storage but when I try to do that by finding and selecting the csv file I want from the cloud, it just takes me back to the list of fields without adding the new file or showing the usual selection menu. I do not get an error message. I have tried with multiple different cvs files that previously loaded fine and I tried on 3 different android devices since the start of this new requirement to define a storage location, and I cannot get any new fields to load on any devices. When I try to add the cvs file to Local Storage, I cannot even find the folder that I defined as the storage location. I can see it when I go to settings -> define storage location, but it no longer shows up in my list of internal storage folders so I cannot put any files in there. 

**Device Info (please complete the following information):**
 - Model: Galaxy S10 and I also tried multiple different galaxy tablets
 - OS: Android 11
 - Field Book Version 5.2.5

**Comment by trife** [comment]
Hi @rachelgreenh can you test the v5.3 beta to see if this solves the issue?

https://github.com/PhenoApps/Field-Book/releases/download/v5.3.0/Field-Book-v5.3.0a.apk

**Comment by rachelgreenh** [comment]
It did not solve the issue.

**Comment by trife** [comment]
When you say you can't see it in the list of folders do you mean on device or via computer? If you selected the existing `fieldBook` folder there really shouldn't be any reason you can't see it. This is really strange so we'll definitely look into it. Once you've finished this season/experiment, it might make sense to start from scratch, delete any existing Field Book directories, and create your own directory.

We didn't want to have to take the storage definer route but the alternative was substantially more painful and confusing.

**Comment by rachelgreenh** [comment]
I finally found the defined folder on my phone. It was only showing me "essentials" and when I select "all" I can see it now. I think this is new since I updated my phone. Now I can add from local storage but still not from the cloud.

**Comment by trife** [comment]
@rachelgreenh which cloud service are you trying to import from? If you have any others installed on your device could you test those out to see if you get the same behavior?

**Comment by rachelgreenh** [comment]
I use onedrive. I just tried loading a file from google drive and that did work. It's very strange since I have always used the same one drive folders. I tried loading an old file that I know previously loaded and nothing happens. It just brings me back to the list of fields in the app.

**Comment by trife** [comment]
The storage definer update was (behind the scenes) huge for file management and transfer, so it's likely something just broke with how we were parsing OneDrive files. @chaneylc can look into this next week to see if we can recreate the issue. Going to rename the issue to better reflect the problem.

**Comment by rachelgreenh** [comment]
thanks so much for your quick response! I use fieldbook nearly every day for my work and I love it.

**Comment by trife** [comment]
The beta version with a fix for this issue can be downloaded from [here](https://github.com/PhenoApps/Field-Book/releases/download/v5.4/Field-Book-v5.4.0a.apk). Let us know if you run into any problems.
