### ISSUE TITLE
[BUG] USB  Camera Not Working on Samsung Tablet

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#502]
Hi, I have been playing around with the USB camera trait. It seems to work fine on my Google Pixel 5a, but I can't get it to work on my Samsung tablet (https://www.amazon.com/SAMSUNG-Android-Compact-Lasting-Battery/dp/B094Q89NKH/ref=sr_1_3?crid=CKTDONORUS8F&keywords=samsung+tab+a7+lite&qid=1663163394&sprefix=samsung+tab+a7+lite%2Caps%2C94&sr=8-3) . The camera is recognized, but then it just shows a blank area after connection.
![tablet](https://user-images.githubusercontent.com/36375878/190172834-c6305ed5-70ee-41c7-ac34-8e5b63248651.jpg)

**Comment by chaneylc** [comment]
@ch728 Do you know what version of Android your tablet is running?

**Comment by ch728** [comment]
@chaneylc Android 11

**Comment by trife** [comment]
I finally got a chance to test this on a Samsung tab I have (SM-T500) and it worked with a Logitech webcam with no issues. @chaneylc what additional debug info would be helpful?
@ch728 do you have a different webcam you can test with this tab to see if it's an interaction issue?

**Comment by chaneylc** [comment]
@ch728 Can you give a brief description on what you do to repeat this? The USB camera trait should have a single button, when you press that does a permission dialog pop-up?

**Comment by ch728** [comment]
@chaneylc  I see the button, I click it and grant permission, but then it displays a blank screen

![IMG_20220922_112104_575](https://user-images.githubusercontent.com/36375878/194051981-78c008fd-390f-457d-997f-25c7ef75aaac.jpg)

![IMG_20220922_112114_151](https://user-images.githubusercontent.com/36375878/194052017-6b799db4-cbcd-4e6b-abd7-711e910534a2.jpg)

**Comment by ch728** [comment]
@trife I tried with a nexigo usb camera and it sort of works. Quality is very bad, see picture below. I don't have issues with either on my Pixel 5A device. What specific Logitech camera have you tested? These are the two cameras I have tested https://www.amazon.com/gp/product/B08931JJLV/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1 and https://www.amazon.com/SVPRO-Resolution-3264x2448-Computer-Windows/dp/B07CSKXB72/ref=sr_1_3?crid=35H6NYF5A58LB&keywords=usb+camera+manual+focus&qid=1664970336&qu=eyJxc2MiOiIzLjcwIiwicXNhIjoiMy4yNCIsInFzcCI6IjAuOTIifQ%3D%3D&s=electronics&sprefix=usb+camera+manual+focus%2Celectronics%2C90&sr=1-3&ufe=app_do%3Aamzn1.fos.006c50ae-5d4c-4777-9bc0-4513d670b6bc

![IMG_20220922_143632_482](https://user-images.githubusercontent.com/36375878/194052481-93203359-5eac-4e9d-980c-55c3bb48c312.jpg)

**Comment by trife** [comment]
The [Logitech C920e](https://smile.amazon.com/Logitech-Mic-Enabled-Certified-Microsoft-Compatible/dp/B09DVGV7BH) but I was testing it with Pixel devices. Chaney did all of his testing with a [generic USB cam](https://www.amazon.com/gp/product/B07PBHM7KV) similar to the one you have. I tested with an Samsung A7 and it worked fine; I don't know what they would have changed for the A7 Lite to break so much.

I'm traveling for the next week or so but can order one of these to use as a testing device once I'm back in SC.

**Comment by trife** [comment]
@ch728 Just to follow up on this- we were recently awarded an AG2PI coconut seed grant to improve/extend this functionality and identify/define hardware for image capture with external data collection. So... we're working on it and will hopefully have some updates in the next few months.

**Comment by ch728** [comment]
Great news! I did eventually find a camera that works https://www.amazon.com/MOKOSE-Desktop-Streaming-Calling-Computer/dp/B08FHBRKSK?pd_rd_w=m1Bxi&content-id=amzn1.sym.deffa092-2e99-4e9f-b814-0d71c40b24af&pf_rd_p=deffa092-2e99-4e9f-b814-0d71c40b24af&pf_rd_r=SBCR91JJ0QJCAS0XRMYQ&pd_rd_wg=Sui1P&pd_rd_r=fb6d658d-9118-4cb8-bc90-cf8cbf76c486&pd_rd_i=B08FHBRKSK&ref_=pd_bap_d_grid_rp_0_8_t&th=1 . Not sure what is special about this one versus others.

**Comment by trife** [comment]
That's awesome! I'm going to go ahead and close this for now and I'll follow up over email.
