### ISSUE TITLE
[BUG] Bluetooth Scanner Only saving first character

### ISSUE THREAD

**Issue by zrm22** [PhenoApps/Field-Book#510]
**Describe the bug**
When connected to a Bluetooth scanner, whenever a barcode is scanned in, Fieldbook will only record the first character instead of the entire string.  This used to work correctly in previous version of Fieldbook and we can get up and running if we go back to version 5.1.  5.2 and current master do not work correctly.  Bluetooth connection works correctly, if we open up a notes app, the full text is stored as expected.

**To Reproduce**
1. Load in a field
2. Create a Text trait
3. Go To Collect Menu
4. Scan barcode
5. Only first character of barcode string is stored in the TextLabel, nav moves to next trait. 

**Expected behavior**
We expect the full text of the Barcode to show up in the Text Label.  

**Device Info (please complete the following information):**
 - Model: Motorola MotoG Power 2021-2022
 - OS: Android
 - Field Book Version 5.2 has bug, 5.1 is fine

**Comment by trife** [comment]
@zrm22 Can you test out the behavior with each of the options for the 'Return key signal' setting selected (in Settings > Behavior)?

@chaneylc Any idea what would be causing this?

**Comment by zrm22** [comment]
@trife I can when I get a chance.  I need to track down a scanner which is not being currently used in the field.  Oddly enough it would not always do just the first character, sometimes the 2nd as well, but never the full string.  

Just for info, our barcodes are in the form ee#100.  We use the '\n' character as our return.  

I will also try the built in scanner as well.  Its not ideal for our use case though because we scan against a continuous barcode taped to a 6-7ft long stick.  Each cm is a different code and having the red laser line showing up on the tool as we scan makes it very easy to see and verify that we hit the correct mark on the stick in the field(especially when it is sunny).  A camera based barcode scan might be trickier to get right.  I will test though when I get a chance.

**Comment by trife** [comment]
I wasn't suggesting to use the camera to replace the scanners, only curious if the behavior was present on both. 

The return key signal setting only changes the interpreted behavior of the `\n` character that's included with the barcode. Since you're going to next trait with that character, I was wondering if we are doing something incorrectly with that interpretation so checking across all three settings would provide some debug evidence for that.

Can you also post a clear pic of the barcodes you're using? I can't find info about ee#100 barcodes.

**Comment by zrm22** [comment]
Yep, I will check the camera and the return key signal setting when I get a chance(should be in 1-2 days).

The barcode format we use are not a common standard, but they can be read by any scanner. They just have 2 characters for the tool id(ee in my example), a # to separate and then the 3 digit value(100 in my example).  So if the scan returned the string ee#150 we know its the ee tool and the measurement was 150 cm(unit based on tool). In a very old hacked version of field book we used we actually parsed out the ee# and just stored the measurement, but that was very specific to our use case.  Now we just take the whole String and do some post processing before we sent to Breedbase via external load.  I will try to post a clean picture of what our tools look like.

**Comment by zrm22** [comment]
![20221013_123713](https://user-images.githubusercontent.com/54960003/195655846-f698512e-3060-4191-bec8-7073f0c4ee86.jpg)

**Comment by trife** [comment]
@chaneylc Do you have a barcode scanner you can use to test this? I'm seeing the same behavior on a Pixel 3 with a hardware Zebra Scanner. Check for changes to current value edit text between 5.1 and 5.2- I think this might be related to the listener code, but could be wrong.

**Comment by trife** [comment]
Fixed in 9675964653be766615fbbad66b99e408bf962049
