### ISSUE TITLE
BrAPI authentication not working with Breedbase [BUG]

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#516]
Using V5.3, I am seeing this error when trying to authenticate:

![IMG_20221031_155859](https://user-images.githubusercontent.com/36375878/199102138-b0f74e93-27ba-49c8-a7f4-b858b7de9a63.jpg)

I don't recall seeing this error before. My understanding is FieldBook needs to match something in this line in the breedbase conf https://github.com/solgenomics/sgn/blob/master/sgn.conf#L404

**Comment by trife** [comment]
Are you using Field Book Custom auth or OAuth2? BrAPI v1 or v2?

**Comment by ch728** [comment]
Turns out I was using the wrong OIDC Flow, needed to be OAuth2.
