### ISSUE TITLE
Traits sorting: get back the original order after sorting the traits

### ISSUE THREAD

**Issue by laguem** [PhenoApps/Field-Book#52]
It would be nice to add the possibility to get the traits in the original order (traits order in the original file after importing) after sorting them.  The option could be added in the sorting menu.

**Comment by trife** [comment]
This will require some changes to the traits table since the original order information is not currently saved, but should be feasible.

**Comment by laguem** [comment]
Another option would be to allow users to manually reorder the traits by dragging the traits on a list and drop it at the right place (drag and drop).

**Comment by trife** [comment]
Drag and drop to reorder is already available using the three line bar on the edge of each trait.

**Comment by laguem** [comment]
I've just tried and I can't move the traits by using the three line bar on the edge of the traits.  I'm using a Samsung tablet (SM-T380 with Android 9 and Fieldbook 4.0.3)
