### ISSUE TITLE
Some bugs in three activities

### ISSUE THREAD

**Issue by m-inamori** [PhenoApps/Field-Book#53]
I downloaded PhonoApps_hack_2019 brank and tried to arrange FieldEditorActivity, TraitEditorActivity, and MainActivity because of their classes have so many fields.
In the process, I found some bugs.

1. In FieldEditorActivity etc. we make it to the background and leave it a few minutes (2 minutes in my environment), and make it to the foreground. Then Field Book crashes.
2. When editing a trait in FieldEditorActivity not in English, the previous format is kept.
3. In FieldEditorActivity, relationship among initial, minimum, and maximum values is not checked.
4. MultiCategory trait does not work.
5. In Category and MultiCategory, category duplication is not checked.
6. In MainActivity, if the minimum or maximum value is set for the trait for which data is being entered, the data will not be saved.
7. In MainActivity, when long pressing leftRange, Field Book crashes in HIDE_ENTRIES_WITH_DATA mode.

**Comment by trife** [comment]
Hi @m-inamori , if you'd like to make a pull request against the development branch, I'd be happy to incorporate your changes into the next app release.

**Comment by m-inamori** [comment]
Hi Trevor,
Thanks.
I'm grad to collaborate with you.

**Comment by trife** [comment]
6633dcee49336104f23cad7a1b0c406868efc008
