### ISSUE TITLE
[BUG] Data collection interface indicates null navigation values

### ISSUE THREAD

**Issue by lagvier** [PhenoApps/Field-Book#532]
**Data collection interface indicates null navigation values**
We have noted an issue with this application where after importing the fields and collecting data after a short while, both the primary and secondary navigations becomes null and it becomes impossible to collect to data for the affected field. 

*summary of the issue*
After importing field and start to collect data, the number of identifiers are two rows then it changes to then 3 then 4 . Finally, the navigation fields become null as shown in the screenshot.

![image](https://user-images.githubusercontent.com/2693136/211816450-195e473b-eb1e-4f78-8146-affb97a6c91b.png)

**Comment by trife** [comment]
@lagvier Can you try installing v5.3 (downloadable from [here](https://github.com/PhenoApps/Field-Book/releases/download/530/Field-Book-v5.3.0b.apk)) and reimporting the field to see if you have the same issue?
