### ISSUE TITLE
[BUG] Image data export

### ISSUE THREAD

**Issue by leetaei** [PhenoApps/Field-Book#538]
Exporting image data (metadata of an image data) does not wrok.

The "null object reference" error takes place when you try to export image data (Figure 1).
This is due to changes in how directories and files were handled on the last release of Field Book.

Figure 2 is the screenshot of the 2 file objects got null when I tried to export the image metadata.

This is what Peter wrote in the email and I think it helps to debug.

"_Image binaries are stored on the phone file system, and the path to that image file is stored in the FB database. There was some mix up of old and new code. When retrieving files, the FieldBookImage class knows the directory where images should be stored, then looks for the specific file name. However, the database now stores the complete file path, not just the name. So it ends up looking for something like this (paraphrasing, not a real path) “/root-storage/FieldBook/data/TrialName/root-storage/FieldBook/data/TrialName/img_2023-01-01_01-01-01.jpg_”

Figure 1
![I_FIG 4 image_error](https://user-images.githubusercontent.com/22690825/220686809-80984707-c956-4b0a-976e-1bcf81047aba.png)

Figure 2
![I_FIG 2 loadINewImages](https://user-images.githubusercontent.com/22690825/220687638-2e489f45-0185-454d-ba8b-aa7691fae2d0.png)

**Comment by chaneylc** [comment]
Fixed this in the #537 branch. This is not merged into develop yet, but you can clone that branch and test if you're interested.

**Comment by trife** [comment]
The beta version with a fix for this issue can be downloaded from [here](https://github.com/PhenoApps/Field-Book/releases/download/v5.4/Field-Book-v5.4.0a.apk). Let us know if you run into any problems.
