### ISSUE TITLE
Not able to import fields to the app [BUG]

### ISSUE THREAD

**Issue by bangira** [PhenoApps/Field-Book#540]
**Describe the bug**
I am not able to import fields to the fieldbook app. We export the fieldbook from Breedbase and put them on onedrive cloud and then import them to the app. We followed the same process last year (2022) and it worked but this year with version 5.3.0 it is not importing fields.   

**To Reproduce**
1. Go to 'fieldbook app'
2. Click on 'click on fields'
3. Click on  'three dots and click import'
4. Select cloud, go to onedrive or any cloud service
5. click on field 
6. and it brings you back to the filedbook app but nothing imports 

**Expected behavior**

When I click on the field from cloud, it should give me option to select primary and secondary identifier and then import the field

**video**
https://user-images.githubusercontent.com/92544145/225080482-1112d656-7ac5-4fa8-a0b3-1841383e4446.mp4

**Device Info (please complete the following information):**
 - Model: [Motorola one 5G Ace ]
 - OS: [e.g. Android 10]
 - Field Book Version [5.3.0]

**Additional context**
We are setting up the phones for this growing season, so please help us

**Comment by chaneylc** [comment]
This is fixed in the #537 branch and will be included in the next version. Thanks @bangira

**Comment by bangira** [comment]
Do you know when next version be out? If not soon, I can use beta version. Thanks @chaneylc

**Comment by trife** [comment]
Beta will hopefully be released this week; release will depend on any issues identified in the beta.

**Comment by trife** [comment]
The beta version with a fix for this issue can be downloaded from [here](https://github.com/PhenoApps/Field-Book/releases/download/v5.4/Field-Book-v5.4.0a.apk). Let us know if you run into any problems.
