### ISSUE TITLE
Intermittent problems with photo traits

### ISSUE THREAD

**Issue by bellerbrock** [PhenoApps/Field-Book#554]
**Describe the bug**
Intermittent problems with photo traits using Fieldbook v5.4 on an S22:
 * At first Fieldbook app crashed when saving a photo - after opening the camera and taking a photo, when pressing the checkmark.
 * After reinstalling Fieldbook, the crashing disappeared, but after being taken photos would not display properly when opened from the collect screen. The first photo for each plot could not be found, viewing any of the remaining photos would display the previous photo.

**To Reproduce**
Install v5.4 on an S22, create a photo trait, and try taking photos.

**Expected behavior**
No crashing, each photo thumbnail to open the correct corresponding photo.

**Screenshots**
https://user-images.githubusercontent.com/11297346/228375888-b061ef7a-4496-4f14-b85c-190b3b227ff0.mp4

Also here is logcat output captured in Android studio, covering the same activity shown in the screen recording.
[FieldbookErrorLog.txt](https://github.com/PhenoApps/Field-Book/files/11094519/FieldbookErrorLog.txt)

**Device Info (please complete the following information):**
 - Model: S22
 - OS: not sure
 - Field Book Version 5.4

**Additional context**
 @ramierop can provide additional context.

**Comment by ramierop** [comment]
Thanks for posting this Bryan. 

My OS is Android 13. Our Pixel 4a's run Android 12. They don't seem to have this issue of crashing. However, they are slow on returning to the Collect page after taking a photo. 

Let me know how else I can be of assistance with this. Thanks1

**Comment by trife** [comment]
This was also identified by another group and we're working on implementing a few fixes related to both integrity and speed for photo collection. I'll push those updates to the beta once they're completed (likely next week).

**Comment by ramierop** [comment]
@trife @bellerbrock 

I downloaded the version you pushed. Not much lag between taking photos and returning to collect data screen. Nice improvement. But, when a trait has multiple photos I can't go expand the first photo like I can for the second or third. 

I will make a fresh trial with no data and see if the issue persists.

**Comment by trife** [comment]
@ramierop Please test the attached version with a few additional fixes and optimizations.

[Field-Book-v5.4.1b.zip](https://github.com/PhenoApps/Field-Book/files/11150977/Field-Book-v5.4.1b.zip)

**Comment by ramierop** [comment]
I will download and test

**Comment by ramierop** [comment]
@trife seems to be working well, can view all the images.
