### ISSUE TITLE
alert user that not all data will be exported when exporting via table

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#576]

**Comment by ramierop** [comment]
I've noticed that while using the beta option for repeated measurements that the repeated measurements are available in the database format only. Seeing that data in the table format would be easier to look at.

**Comment by trife** [comment]
@ramierop it would be difficult to make that both easily parsed and visually pleasing. adding the repeated measures is essentially adding a third dimension to the 2D table format.
