### ISSUE TITLE
Import field from local storage is failing

### ISSUE THREAD

**Issue by dlourido04** [PhenoApps/Field-Book#58]
Immediately I choose the option **Local storage**, the application returns to the main menu. No message is displayed. File is storage at field_import directory.

**Comment by trife** [comment]
Post the device device, Android version, and app version you are using.

Can you verify that all permissions have been granted to the app?

**Comment by dlourido04** [comment]
Device Huawei P10 Lite Model WAS-LX3
Android version 8.0.0
App version 4.1.1

**Comment by trife** [comment]
When it becomes public in the next hour (or if you are comfortable sideloading the release), please update to 4.1.2 and recreate the crash.

**Comment by trife** [comment]
Were you able to update to 4.1.2? Did you confirm that all permissions were granted to the app?

**Comment by dlourido04** [comment]
Hi, Currently I have 4.1.2 version but still crashing, only works with Dropbox to me. Traits is not working with Dropbox and local storage.

**Comment by dlourido04** [comment]
I test in other phone with the same files and it's working without problems: 
Device Samsung Galaxy A50 Model SM-A505G
Android version 9.0
App version 4.1.2

**Comment by trife** [comment]
Did you confirm that all permissions for Field Book were granted in the system settings?

**Comment by trife** [comment]
Can you try opening the Search icon on the Collect Data screen and report the behavior?

**Comment by dlourido04** [comment]
Search icon is not working, return to main menu. I checked app permissions and all of them are ok.

**Comment by trife** [comment]
Ok I've identified the problem and will have a fix out in the next few hours. Thanks for your help!

**Comment by trife** [comment]
3b7c631ecb7f5646809b9bd186857da41eccd06b

**Comment by trife** [comment]
The updated version can be downloaded from here if you don't want to wait for Google Play: https://github.com/PhenoApps/Field-Book/releases/tag/v4.1.3

**Comment by dlourido04** [comment]
Field local storage import is working now! But traits is not working with Dropbox and local storage
