### ISSUE TITLE
[REQUEST]: continual refresh on the GNSS trait for reading the external GPS from bluetooth

### ISSUE THREAD

**Issue by jessepoland** [PhenoApps/Field-Book#618]
### Description

Need to implement a continual refresh on the GNSS trait for reading the external GPS from bluetooth.  When it looses signal it just remains stuck / display / record on the last reading which causes big problem if you move and then record a point, not realizing that it lost the signal and the location is not current.  Need something where it checks every second for an updated NEMA string or something and goes blank if not current.

**Comment by trife** [comment]
Should be fixed by #705
