### ISSUE TITLE
[BUG]: Pipe character in ontology traits causes image to fail

### ISSUE THREAD

**Issue by joegage** [PhenoApps/Field-Book#641]
### Description

When I import traits from BrAPI, they are named along the lines "SomeTrait|OntoName:000001". When I try to take an image for an imported trait, I am brought the the camera, take the picture, am shown a preview, press the check mark, but then no thumbnail appears. In the file browser, there is a directory under plot_data/FIELD/TRAIT, but no images in that directory.

When I create my own trait with a name like "SomeTrait", it works as expected. When I rename my own trait to "SomeTrait|xyz", it fails in the same way described above; so I think the pipe character may be reserved or otherwise causing this to fail.

Hardware: moto g play (2021), Android version 11

### Expected behavior

Image capture works as it should even though there are reserved character(s) in the trait name. OR - on the breedbase side, trait ontology names don't include problematic characters ( I saw a related issue having to do with colons on Windows machines here: https://github.com/solgenomics/sgn/issues/4104)

### Field Book version

5.4.6.11

**Comment by trife** [comment]
I think this is a relatively easy fix on our end, but as discussed in https://github.com/solgenomics/sgn/issues/4104 there could be a indirect effects of modifying image naming. These changes shouldn't affect images uploaded via BrAPI, but I don't know how most breedbase users are uploading images to the system.

@lukasmueller - since trait name and ontology ID are stored in separate fields, what's the motivation for merging them into a single field?

Opinions about sanitizing file names? @BrapiCoordinatorSelby @timparsons 

Semi-related to #400

**Comment by BrapiCoordinatorSelby** [comment]
I agree it shouldn't impact BrAPI export. BrAPI doesn't care what the file names are, as long as they match the value sent in the JSON metadata.

looking at the two ways to import images manually into Breedbase (from https://github.com/solgenomics/sgn/issues/4104) option two (Images with Associated Phenotypes) will always work, doesn't matter what the file names are, just provide the extra metadata to explicitly match images to plots/traits. Option one (Images Alone) will require some development on the Breedbase side to fix this issue. 

One thought, if you have the traits imported via BrAPI, then Field Book has the trait DbId as well as the name. Image files could be named with the DbId instead, and it would still be easy for Breedbase to import those automatically. 

Another thought, follow the POSIX Portable Filename Character Set standard for file names. This standard is meant to be 100% transferable between any operating system or file system. Only dot, dash, and underscore allowed for special characters. 
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282
```
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
a b c d e f g h i j k l m n o p q r s t u v w x y z
0 1 2 3 4 5 6 7 8 9 . _ -
```
