### ISSUE TITLE
[REQUEST]: Do not overwrite traits with new .trt file import

### ISSUE THREAD

**Issue by hkmanching** [PhenoApps/Field-Book#653]
### Description

When importing a trait file, it is required to delete all pre-existing traits before importing. I would like the option to add traits to the pre-existing list instead of deleting the current list of traits.

**Comment by trife** [comment]
@ch728 @hkmanching Turns out the text label on the export dialog was an Android bug and instead of displaying "no" it displayed "cancel" which was confusing. This should be addressed in #764 and you should be able to merge trait files into currently existing traits.
