### ISSUE TITLE
[REQUEST]: GeoNav functionality change based on GPS correction status

### ISSUE THREAD

**Issue by ahulsekemp** [PhenoApps/Field-Book#660]
### Description

Create functionality that will modify function of GeoNav based on GPS correction status. Data should only be collected, or at least user notified, when RTK correction drops. 
Possibilities - audio and/or visual notification on GeoNav page (visual could be changing color of the plot label, perhaps from green currently to red)
Could also disable data collection ability thru GeoNav when RTK correction is dropped.

**Comment by trife** [comment]
Audio notification when location drops is in #705
