### ISSUE TITLE
Theme updates to further support eink devices

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#683]
- [ ] Disable all animations
- [x] No button background color
- [x] Define button outline color
- [x] Detect if boox manufacturer and use updated icon (relates to #166)
- [x] [Replace icon](https://www.mobileread.com/forums/showthread.php?t=316482)

[Potential theme components and colors](https://github.com/sibbl/hass-lovelace-kindle-screensaver/blob/main/lovelace-eink-theme.yml)

**Comment by chaneylc** [comment]
Make sure all dialogs have the black outline as the system dialogs do

**Comment by chaneylc** [comment]
Ask Enable high contrast theme dialog if manufacturer is found
