### ISSUE TITLE
Multiple traits using pictures

### ISSUE THREAD

**Issue by mdzievit** [PhenoApps/Field-Book#7]
Hello Trevor,

First of all, great app, we love it in our lab. Secondly, I appreciate you fixing the issue with including the trait name in the filename when taking pictures. The issue still remains where all pictures show up for photo traits, not specifically that one for the trait. 
For example, you have 2 traits setup to take pictures, if you take a picture for trait 1, go to trait 2, the picture for trait 1 shows up in the thumbnail section and vice versa. Having them separated makes it easier when acquiring the pictures.

Thank you again for a great app!

**Comment by trife** [comment]
This will be fixed in the next version.
