### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#716]
### Description

**Environment:** Samsung Galaxy A12, Android 13, FieldBook 5.4

**Steps to Reproduce**
After entering a BrAPI url and authorizing 
![image](https://github.com/PhenoApps/Field-Book/assets/142930813/3f30bec1-4d0f-4fab-9d3b-5849459d7b77)

I am directed away from the Field Book app to the Play Store
![image](https://github.com/PhenoApps/Field-Book/assets/142930813/642ece0a-e507-4c5b-a89b-922320e5721e)

*Actual behavior:** Selecting Open launches an empty page 
![image](https://github.com/PhenoApps/Field-Book/assets/142930813/04195a7d-74fc-4254-b7b6-8dba4c86d580)

### Expected behavior

**Expected behavior:** Selecting Open will  launch the Field Book App

**Comment by trife** [comment]
Is this with the v5.4 beta on Google Play? Can you test the release on GitHub to check if the behavior is the same?

**Comment by SCYarnes** [comment]
Hey Trevor,

I will load the latest from GitHub later today, and update the ticket with my findings.

Also, I want to invite to our upcoming  product requirements meetings, because the topic will be  DeltaBreed  BrAPI integration with Field Book. Are you available to join Sept 12th?  Your input is obviously critical as we consider changes to FB. I think it would probably also be helpful to have a pre-meeting (me, you, and Tim)  before opening the topic to the entire BI team. I will reach out probably next week to schedule the pre-meeting.

Best,

Shawn Yarnes PhD
Product Owner (she/they/her/them)
Mobile: +1 530 304 1356
Email: ***@***.***

Cornell University, 103 CALS Surge Facility, 525 Tower Road, Ithaca, NY 14853
www.breedinginsight.com<http://www.breedinginsight.com>
Breeding Insight is funded by USDA through Cornell University.
________________________________

**Comment by trife** [comment]
That sounds great- just send me an email once things get more planned.

**Comment by SCYarnes** [comment]
[like]  Shawn C Yarnes reacted to your message:
________________________________

**Comment by SCYarnes** [comment]
I just sent the calendar invite for the PR meeting Sept 12.  You will notice that the meeting is recurring weekly, but we rarely meet every week. It will probably take a few of these meetings to cover Field Book BrAPI integration.

Shawn Yarnes PhD
Product Owner (she/they/her/them)
Mobile: +1 530 304 1356
Email: ***@***.***

Cornell University, 103 CALS Surge Facility, 525 Tower Road, Ithaca, NY 14853
www.breedinginsight.com<http://www.breedinginsight.com>
Breeding Insight is funded by USDA through Cornell University.
________________________________

**Comment by SCYarnes** [comment]
Hi Trevor, I just tested on v5.5. This is not an issue on the latest code.
