### ISSUE TITLE
[REQUEST]: Return to first trait when advancing to next plot

### ISSUE THREAD

**Issue by tyrwh** [PhenoApps/Field-Book#722]
### Description

Allow user to return to first trait in active trait list when advancing to next plot.

For example, if user has active traits A/B/C/D, enable option such that hitting Next Plot arrow from Plot 1/Trait C proceeds to Plot 2/Trait A, instead of Plot 2/Trait C.

Motivation: Users have core traits scored on every plot and secondary traits scored on occasional plots. Ideal workflow is to quickly advance from plot to plot on core traits, but have secondary traits available to capture when needed.

### Alternatives

Two current workarounds for this. One option is to deactivate secondary traits, activate them when needed for a single plot, and deactivate them after recording for a plot. Second option is to have core and secondary traits active, then hit Next Trait arrow to skip through secondary traits on each plot.

**Comment by trife** [comment]
I like this. This is similar to [this setting](https://docs.fieldbook.phenoapps.org/en/latest/settings-behavior.html#repeat-cycling-traits-advances-entry), but different.

**Comment by tyrwh** [comment]
Yeah I pretty much always have that option on and recommend others do the same, would be great to extend the functionality. We've got users doing core traits on all plots, with the occasional note or disease incidence trait here and there. Skipping past the auxiliary traits would be useful, streamline the workflow
