### ISSUE TITLE
BrAPI Export: New & Synced Observations count

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#726]
5.5.12

I made 2 observations and selected BrAPI export. The count showed erroneously 4. I exported to DeltaBreed via BrAPI and the sync count showed erroneously 4. Looking at DeltaBreed I am able to confirm that 2 observations were uploaded.

**Comment by chaneylc** [comment]
I haven't been able to reproduce this yet. What kind of trait were you using? If it has a default value then Field Book will create an observation when that plot/entry is visited (without actually entering data).

**Comment by SCYarnes** [comment]
@chaneylc 
I haven't encountered this lately, and it hasn't been flagged by anyone else on our team. Feel free to close the issue. Thanks!
