### ISSUE TITLE
[BUG]: Barcode Value Not Recording

### ISSUE THREAD

**Issue by maizeatlas** [PhenoApps/Field-Book#734]
### Description

Hello. We have a Google Pixel 7a and an Inateck BCST-54 Barcode Scanner. When we scan barcodes (e.g., using Fields==field_sample and Traits==height and the height barcode sheet from the GitHub site), we get a beep and the plot advances as if a value is recorded, but in fact no value is recorded. We have not changed the apps system settings. Using the apps barcode button to activate the phone camera works and records the expected value, but the camera is too difficult to use. We tried changing the trait format to text. In that case, it records a value but not the one corresponding to the barcode (e.g., it records a value of "1" for all barcodes). We tried the barcode scanner via bluetooth and wired modes and have the same result. Using a notes app on the Pixel, we confirmed that the barcode reader will scan the correct values from the barcode sheets, so the issue appears to be a specific problem between the scanner and field book. Any ideas about what the problem could be?

### Field Book version

5.3.0

**Comment by trife** [comment]
This has been fixed in the latest version which you can download from [Github releases](https://github.com/PhenoApps/Field-Book/releases/latest). It's currently in beta on Google Play and will be promoted to full release next week.

**Comment by maizeatlas** [comment]
Thank you. That was an incredibly fast response. I just tried the beta version (5.5.14). If I enter the search bar, say in the settings on the fieldbook app, it scans the expected value. When I go to Collect, it no longer advances after clicking the reader and still no value is recorded.

**Comment by trife** [comment]
Are you using the default traits? i.e. Is the height you're trying to scan a numeric trait or text trait? I think the current setup is only compatible with external barcode scanners for text traits.

**Comment by maizeatlas** [comment]
That's it. If we set the format to text it works. Thank you!
