### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by keocorak** [PhenoApps/Field-Book#735]
### Description

V5.5.13 dowloaded from APK
Uploaded field layout file attached: [2023Nursery_NorthEast2.csv](https://github.com/PhenoApps/Field-Book/files/12662702/2023Nursery_NorthEast2.csv), which has some lat;long coordinate data in a 'geo_coordinates' column. 

I'd expect and like to see data from this column in the info bars, but instead I see 'null'. 'geo_coordinates' window of the Summary tab is likewise empty. Also, If you try to view coordinates in the row names of the data grid (TBH, I'm not sure why you would do this), the app crashes. 

### Expected behavior

Allow viewer to see geo_coordinates data as a confidence check in both summary view and info bars. 

### Field Book version

5.5.13

**Comment by chaneylc** [comment]
@keocorak I added a PR https://github.com/PhenoApps/Field-Book/pull/736 If you could test the APK that is built there that would be helpful, thank you.

**Comment by chaneylc** [comment]
Also, what primary/secondary id's do you use? I was able to get your file to work, but initially I chose the first two columns and it imported 0 plots which crashed the app when moving to Collect, which is probably a different issue.

**Comment by keocorak** [comment]
Hey Chaney, sure I'll test the #736 PR and let you know. And the second column is the problem in the file I attached. It's actually empty except for the header, which is why no plots are imported.

**Comment by keocorak** [comment]
As of 5.5.18.78, fixed
