### ISSUE TITLE
[BUG]:  V.5.5.16.71 - multicat delete selection while changing sample if more than one selected - Samsung Galaxy Tab S8

### ISSUE THREAD

**Issue by coulombevin** [PhenoApps/Field-Book#751]
### Description

1. I've just updated the app to 5.5.16.71 and since then the multicat is saving the trait for a sample only if one cat is selected. When I select two or more cat in the same multicat trait and I go to the next sample, the trait is erased instead of saving it. So when I go back to the first sample, the multicat field is empty.

2. Also, when I click on the already made multicat trait for , I get a huge button with "Yellow/Purple/.." instead of getting multiple buttons.

Those error doesn't happen on my cell phone (Samsung Galaxy S22) only on my tablet (Samsung Galaxy Tab S8).

Info
---
- App version: 5.5.16.71
- Device: Samsung Galaxy Tab S8
	- One UI: 5.1.1
	- Android: 13
	- Kernel: 5.10.136-android12-9-27102101  

### Expected behavior

1. Save more than one cat in the multicat.
2. Have a button for each cat.

### Field Book version

5.5.16.71

**Comment by trife** [comment]
@chaneylc

**Comment by trife** [comment]
@coulombevin I'm unable to replicate this issue on my test device. The huge button issue should have been resolved in 5.5.16. If you can upload or email a database dump (Settings > Database > Export), @chaneylc can look into this further.

**Comment by coulombevin** [comment]
@trife Thanks for your time, we've done the new patch from the app (not google play) and everything is back to normal.

**Comment by trife** [comment]
@coulombevin Great! Let me know if you run into any other issues.
