### ISSUE TITLE
[REQUEST]: Modify brapi import procedure

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#761]
### Description

Current behavior

1. Select observation level from all program defined levels
2. Select Field
3. Display field-level summary stats
When the selected level is not relevant to the field, the stats are nonsense. The user must then return to step 1 and select a relevant level.

Desired Behavior

1. Select field
2. Select observation level from relevant options
4. Display field-level summary stats

### Additional Context

The current behavior isn't a blocker, but is a little confusing. Trevor mentioned upcoming changes to the workflow, so perhaps this change might be considered as a part of the larger effort. I identified this issue as I reviewed interoperability between FB and BreedBase - the issue remains as a nice-to-have improvement for FB-DeltaBreed interoperability.

**Comment by trife** [comment]
It has to be enabled in experimental settings, but this is fixed in v6 and will graduate to on by default before EOY.
