### ISSUE TITLE
[BUG]:  BrAPI Connection to Breedbase Not Working

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#777]
### Description

Using version 5.4, I was able to connect to my breedbase instance and authenticate. Using version 5.5, the authentication doesn't work. The app just blinks a quick error connecting to server message.

**Comment by trife** [comment]
What's the full version number you're using? Can you post a screenshot of your brapi settings?

**Comment by trife** [comment]
@ch728 Did Lukas get in contact? It sounds like this may be a server config issue.

**Comment by ch728** [comment]
Currently using 5.5.24. Tested again today and the authentication started working. Maybe the app updated since I last used it. The BrAPI trait import works, but the field import does not. The field list load, but  I get an error when I try to save the field. It says there are no plots when there are indeed plots.

**Comment by trife** [comment]
Can you double check when importing the field that the observation level is set to plot when importing?

**Comment by trife** [comment]
Closed. Will reopen if issue comes back.
