### ISSUE TITLE
[REQUEST]: Update to SDK 34

### ISSUE THREAD

**Issue by chaneylc** [PhenoApps/Field-Book#780]
### Description

https://developer.android.com/about/versions/14/behavior-changes-all

Looks like there are partial media permissions, which might require changes to how media is stored in FB. I noticed that if I open the partial selection intent, and don't choose anything the app will crash.

**Comment by trife** [comment]
Are field book images added to the system gallery? I'd hope that since we're saving them in a custom location that this isn't as much of an issue.

**Comment by trife** [comment]
Also update any dependencies as needed for this issue

**Comment by chaneylc** [comment]
Related #812
