### ISSUE TITLE
[BUG]: InfoBar updates

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#785]
- [x] Make attributes the default option when opening the infobar prefix selector
- [x] geo_coordinates is often showing up by default with `null` value but shouldn't be visible from the infobars (especially as default)

**Comment by bellerbrock** [comment]
#781 includes a fix for the geo_coordinates issue

**Comment by trife** [comment]
Do you want to go ahead and include adjust the default tab in the selector to be attributes so that PR can close this issue as well?
