### ISSUE TITLE
Problem with backspace\delete in text trait on Samsung devices

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#786]
### Discussed in https://github.com/PhenoApps/Field-Book/discussions/782

<div type='discussions-op-text'>

<sup>Originally posted by **rlmorgan7** October 26, 2023</sup>
I've just updated to the latest version (v 5.5.16). The only problem that I have found is that when typing on the tablet keyboard in the text trait, the delete and backspace buttons don't work. I'm using a Samsung Tab A7 Lite tablet. Has anyone else seen this problem/found a solution?</div>

**Comment by chaneylc** [comment]
@trife this doesn't seem like an issue anymore on latest version of main

**Comment by rlmorgan7** [comment]
@trife  I upgraded to Version 5.6.2
The issue is now slightly different. The backspace and delete work but now delete everything that has been typed into the text box when pressed, instead of just deleting the last character (or where the curser is placed).

**Comment by trife** [comment]
@chaneylc Can you test this on your Samsung after you finish the eink updates?

**Comment by trife** [comment]
@rlmorgan7 I'm seeing some weird behavior with this on a test device I have- it looks like a Samsung keyboard problem 🤦

If you install GBoard from the Play Store, this behavior should go away. We'll still work to figure out the issue with the Samsung keyboard, but this will be a quicker fix.

**Comment by rlmorgan7** [comment]
@trife I've installed GBoard, that did solve the problem. Thanks!
