### ISSUE TITLE
NA Button Blocks backspace on LG G4

### ISSUE THREAD

**Issue by mdzievit** [PhenoApps/Field-Book#8]
Not sure if this is a phone specific problem, but the NA button for entering numeric data blocks the backspace button.  I have attached the picture for you to see.
I am running Fieldbook version 3.3.1, and android version 6.0.
Thanks,
Matt
![screenshot_2017-07-12-12-47-44](https://user-images.githubusercontent.com/6362549/28131850-cc1c93b0-6700-11e7-9f73-08fc4f807fd9.png)

**Comment by trife** [comment]
Thanks, Matt. This is fixed in the next version which should come out within a week.
