### ISSUE TITLE
[BUG]: Some search features not working while searching for plots 

### ISSUE THREAD

**Issue by akshat22** [PhenoApps/Field-Book#801]
### Description

When searching for plots in collect activity, some filters aren't working.
- 'less than' not working but 'more than' is working for integer values.
- 'is equal to' not working for string values.

**Comment by akshat22** [comment]
Using multiple filters by using the 'add' button in the search dialog also doesn't work.

**Comment by trife** [comment]
@akshat22 was this fixed with your PRs?

**Comment by akshat22** [comment]
Yes, this was fixed as well.
