### ISSUE TITLE
[REQUEST]: Sensible defaults for trait formats for some imported traits with ontology information

### ISSUE THREAD

**Issue by noahddewitt** [PhenoApps/Field-Book#881]
### Description

Apologies if this is not practical -- but trying to test out BrAPI field loading and syncing across many android phones, it would be useful to have sensible defaults for the trait format field, instead of formatting to text. For example, wheat Heading time -day|CO_321:0001235 could default to date. Traits with a 0-9 scale could default to numeric, etc.

**Comment by trife** [comment]
This should be possible now with BrAPI 2.1 but is a breedbase issue of not sending field book the correct format. @lukasmueller can comment further.

**Comment by lukasmueller** [comment]
Hi, good to know that it's a Breedbase issue. I created a ticket for this in the Breedbase GitHub repo at:
https://github.com/solgenomics/sgn/issues/4804

**Comment by trife** [comment]
I think this is fixed. Reopen if it's still an issue.
