### ISSUE TITLE
[BUG]: Domain as localhost in access request URL for BrAPI authorization

### ISSUE THREAD

**Issue by noahddewitt** [PhenoApps/Field-Book#886]
### Description

May be related to issue #880. BrAPI access to a local Breedbase instance (in this case, the T3 version of Breedbase) is configured in Fieldbook as follows:

![Screenshot_20240208-125833](https://github.com/PhenoApps/Field-Book/assets/82885768/ddd3a110-8e7a-4d3d-998c-4df7477ce9d1)

Importing field trial and trait from Breedbase server through BrAPI works as expected. On export, Fieldbook correctly identifies the number of new observations in trial (in this case, will be the first observations recorded for that trial):

![Screenshot_20240208-122948(1)](https://github.com/PhenoApps/Field-Book/assets/82885768/3cb83b64-e451-43ae-844c-7725c4129b8d)

On clicking export, it generates a URL intended to load a prompt on the Breedbase server to authorize export access. Instead of using the previously specified domain, it generates a url with root as localhost followed by the default Breedbase port (8080):

![Screenshot_20240208-115534](https://github.com/PhenoApps/Field-Book/assets/82885768/73047e10-bec1-46e2-b7b9-3003daf2ca07)

If I manually copy the the URL, sub out the root domain for the domain listed in the BrAPI settings, it correctly generates the prompt and allows me to click "authorize":

![Screenshot_20240208-115631](https://github.com/PhenoApps/Field-Book/assets/82885768/b461e7d8-f437-4660-a585-5ad04b30c23d)

(I haven't tested dropping the port. In our NGINX configuration subdomain "sgbreedbase" redirects to 8080).

While Fieldbook does not recognize that the export has been succesfully completed (displaying the same screen as before), the exported observations are viewable in Breedbase in the trial view and as a phenotype upload event with the correct timestamp:

![Screenshot from 2024-02-08 12-52-09](https://github.com/PhenoApps/Field-Book/assets/82885768/79aba6b3-153c-4c56-a558-b43443e655aa)

This issue occurs each time we export to our Breedbase instance across multiple phones, and Fieldbook does not "remember" the authorization. I can re-export the same observations and it maintains that they're "new" observations. 

Not sure if this is a Fieldbook issue or a Breedbase issue. Let me know what additional info would be useful!

### Expected behavior

On first export, should directly load the authorization page from within the app, on export give a visual indication of successful, and if attempt to export again indicate that the loaded observations are not new observations. On collection of new observations, should export the new observations without needing to re-authorize and give a visual indication of a successful export. 

### Field Book version

5.6.4

**Comment by trife** [comment]
@BrapiCoordinatorSelby, you've dabbled in both spaces enough to best answer where the fault lays here. Thoughts?

**Comment by noahddewitt** [comment]
Thanks Trevor. Maybe this will be helpful in debugging? We finished recording the phenotype for this trial yesterday, and I attempt to export the full data set of 1000 observations for the whole trial (the 745 exported yesterday + 255 additional phenotypes):

![Screenshot_20240209-105309](https://github.com/PhenoApps/Field-Book/assets/82885768/5c010e88-faa2-4e23-8359-98400839d99a)

Because of the issue with the synchronization this shows up as "1000 new observations". Exporting it prompts for re-authorization:

![Screenshot_20240209-105320](https://github.com/PhenoApps/Field-Book/assets/82885768/21b1d9c2-f0b7-467a-b4eb-a337ba6a23ad)

... with the same localhost url as before generated on clicking "Log in to site". In case it's helpful, that generated URL is "http://localhost:8080/user/login?goto_url=%2Fbrapi%2Fauthorize%3Fredirect_uri%3Dhttps%3A%2F%2Ffieldbook.phenoapps.org%2F". As before, replacing localhost with the correct root URL properly redirects to the prompt to authorize on T3 Breedbase:

![Screenshot_20240209-105422](https://github.com/PhenoApps/Field-Book/assets/82885768/aeab80dd-c9d6-45f6-97f3-dd212b6d3d08)

This time, however, on returning to the export screen we get a message that says "Export failed":

![Screenshot_20240209-105539](https://github.com/PhenoApps/Field-Book/assets/82885768/ead646c1-8850-4833-8d8c-04ede3c39c32)

Interestingly, if I immediately try to repeat it and re-authorize, it then says that there are *2000 New Observations*. On leaving the screen and re-entering, it goes back down to *1000 New Observations*. 

Syncing in this case returns the same screen as in issue #880, getting stuck on the spinner and failing to resolve in success or error:

![Screenshot_20240209-105619](https://github.com/PhenoApps/Field-Book/assets/82885768/4a81c522-c5bf-4301-ad22-a56d8f7e27db)

Checking out the T3 Breedbase record, you can see the upload of the 745 observations from yesterday, but it doesn't register any attempts today:

![Screenshot from 2024-02-09 10-57-47](https://github.com/PhenoApps/Field-Book/assets/82885768/abcfac65-8409-4cd6-8703-6c0a7749d2bb)

Thanks again for your help with this!

**Comment by BrapiCoordinatorSelby** [comment]
hey @noahddewitt, couple of things to check:

First can you go to Settings >> BrAPI >> Auth Settings and tell us what values are set for `OIDC Flow` and `OIDC Discovery URL`
They should be "OAuth2 Implicit Grant" and "http://sgbreedbase.agcenter.lsu.edu/.well-known/openid-configuration" respectively.

Second, can you please go to that Discovery URL in a browser http://sgbreedbase.agcenter.lsu.edu/.well-known/openid-configuration and report back the content you see there. I assume this server is hidden behind the LSU internal network, so I can't take a peak from the outside.

I suspect that either that Discovery URL is wrong (config change in the app), or the contents of its response are wrong (config change on the server). 

If both of those turn out to be correct, then we can start looking for bugs in the app.

**Comment by noahddewitt** [comment]
Hi @BrapiCoordinatorSelby, thanks for the advice. The fieldbook app looks correct -- OIDC Flow is "OAuth2 Implicit Grant", OIDC Discovery URL is "http://sgbreedbase.agcenter.lsu.edu/.well-known/openid-configuration".

It looks like the Breedbase config may be the thing at fault here. Here's the JSON at that address:

![image](https://github.com/PhenoApps/Field-Book/assets/82885768/5d6deb32-896e-4c96-958b-24ff25354b30)

It turns out I hadn't properly set up my configuration file :) After I added the hostname, I tried recording two fake datapoints on a fresh trial without any data, and authorization worked perfectly in-app. On recording one more faked phenotype, it correctly said "one new observations, two synced observations", and successfully exported without issues or re-prompting for authorization.

The trial from my previous post with the additional data points is still failing to register and showing up as "2000 new observations". Might be related to lack of syncing (#880, which is still not functioning after fixing config) or from previously failing to upload? I might just delete that trial and re-download it. 

Apologies for the trouble, and appreciate your help!

Noah

**Comment by BrapiCoordinatorSelby** [comment]
@noahddewitt Great to hear! I'm guessing that the 2000 new observations are now just broken permanently in the Field Book internal database. it might be a good idea to do a Settings >> Database >> Delete Database just to clear out any broken records from the app. WARNING: this is effectively setting your app back to factory settings with nothing there, make sure you have everything you want to keep first.

@trife Probably should keep this issue open, or open a fresh issue, to address more graceful authentication/export failures. In this case it was just a configuration issue, but it broke the existing FB database records for some reason. That probably shouldn't happen. I don't know exactly whats going on, but more robust failure recovery during export would be really nice to have.
