### ISSUE TITLE
[BUG]: USB cameras record photos in low resolution.

### ISSUE THREAD

**Issue by SimfabFR** [PhenoApps/Field-Book#889]
### Description

There is a problem with the quality of image recording on USB cameras.

I tried to connect 3 different USB cameras, on 2 different devices.

When saving the photo with the application (USB Camera Trait), they are saved in a low resolution. For a single camera tested on 2 Android devices, the recording resolution is different. This could mean that it is not the native image from the camera that is recorded but the preview on the screen of the Android device.

For example, when recording photos with a 4K camera and a 13MP with Fielbook USB Camera Trait, I obtain an image around 1000*800pixels and 1.5Mb.

### Expected behavior

The application should either allow you to save the photo in the highest definition of the camera, or allow you to select from several resolutions on the camera.

### Field Book version

5.6.5

**Comment by trife** [comment]
Do you have a link to the cameras you were testing with?

**Comment by SimfabFR** [comment]
Yes, I tried with the following cameras :
- **http://www.elpcctv.com/elp-128-sony-imx415-color-cmos-sensor-4k-autofocus-usb-camera-module-p-168.html**
- http://www.elpcctv.com/13mp-sony-imx214-sensor-38402880-auto-focus-mini-box-usb-camera-with-75-degree-no-distortion-lens-p-164.html

**Comment by trife** [comment]
@SimfabFR we're testing this and will report back when we have more info- probably in the next few weeks.

**Comment by SimfabFR** [comment]
Hello @trife , by any chance did you get a look on that bug ? Do you know if it will modify in the future ? If so, over what time horizon does this seem possible? Thanks

**Comment by trife** [comment]
@SimfabFR this will be fixed in #898 . It will likely be merged into a release in the next 1-2 months depending on testing.
