### ISSUE TITLE
[BUG]: Datagrid sorting does not match plot sorting

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#906]

**Comment by SCYarnes** [comment]
Hey Trevor, Bi is running into this same issue. I'm pasting in some deets from the team.

> I want to make you aware of an issue AJ and I encountered with the Collect/Grid view in FB after exporting an exp from DB via BrAPI.  It is unclear, at the moment, if the problem is FB- or BrAPI-related.  I will relay this info to Trevor as well.
Below are the steps I followed and my findings.

1. Started FB from scratch - updated to the latest developer version.
2. Made sure DB experiment (AMC, rel-test) was sorted by Exp Unit ID (ascending order) -- this was confirmed by inspecting the downloaded experiment file from DB.
3. Imported program (AMC) into FB.
4. Under BrAPI Field Import, selected:
5. Observation level: Plot, and then
6. One of three Fields (TLH_2024, TLH_2025, TLH_2026).  Note:  I followed these steps with all three of them.
7. On Preview Field, selected plot as both primary and secondary identifiers and saved.
8. Selected all traits.

Selected Collect:
FINDINGS: Collect view was not ordered by Exp Unit ID/plot (order appears at random) and Grid view matches order seen in Collect view.  This was true for each of the three experiments.
Went back to Fields, along side the field name pressed the 3 dots and selected Sort.
Added plot ascending - FB indicated that sorting was updated.
Went back to Collect view.
FINDINGS: Entries are ordered by Plot number in Collect view but in Gridview entries remained in the original order (i.e., random).  This was true for each of the three experiments (see screenshot).

[@AJ Ackerman](https://bi-internal.slack.com/team/U05FZTHJVV4)
 went further with testing and here is what he reported: " Went through every single possible value it could be following and none of them follow anything resembling a sequential order.  We looked at ObsunitDbId, obsunitname, and row/col, and nothing seemed to move sequentially. I've never had a problem with this when uploading trials manually, field book has always operated smoothly as far as plot order goes. Also, usually, field book asks if I am collecting in a serpentine or not, and I haven't been able to find that option with Brapi import; I could be missing it. 
Same for grid view. Plot and row/col do not seemed to be organized in a way I would expect
I did use plot/plot as primary/secondary ids, then tried row/col. Nothing moves in a desired order.
Double checked and the experiment was ordered correct as well in DB and when downloaded on excel.
