### ISSUE TITLE
Fields not uploading Via BrAPI[BUG]: 

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#954]
### Description

Steps to reproduce

- Update existing FB to latest v5.6.15
- Use BrAPI autoconfigure settings to scan DB QR code from DeltaBreed
- Approve connection to FB
- Filter by trial
- Select trial
- Preview Field
- Result => Infinite spinning wheel. Cannot choose primary & secondary identifiers. Cannot load field. Cannot collect data.

Workaround
Revert to v5.6.13 (haven't tested v5.6.14)

### Field Book version

5.6.15

**Comment by trife** [comment]
I'm able to connect to both the test server and CassavaBase and import fields without any issue. Is it possible this is an issue with the QR scan not populating all settings correctly? 

Can you set @bellerbrock up with a test account for DeltaBreed? He'll be at BrAPI hackathon next week and can investigate this issue if there's time then.

**Comment by SCYarnes** [comment]
@bellerbrock You will need to set up an ORCID and share that email address with me or (Dave M, who is in Germany), and then we can set you up on a test server. FYI - I first made this bug ticket for DeltaBreed, but the team thought the fix was needed on Field Book. Feel free to chat with Dave or reach out to me. I still have our bug ticket open, in case we do need to make changes.

**Comment by SCYarnes** [comment]
@bellerbrock Thanks for investigating. I will start a new ticket in our queue, and reference this thread. You may hear back from someone.
