### ISSUE TITLE
[BUG]: Export and Gridview in Fieldbook 5.16.15

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#956]
### Description

From Alexandra M Casa (Breeding Insight)
 [7 days ago](https://bi-internal.slack.com/archives/C04LF1ULHD2/p1712590409247039)
Anybody else having issues with Export and Gridview in Fieldbook 5.16.15?  When I click on Export, the app quits and when I select Gridview, I get the spinning wheel

**Comment by SCYarnes** [comment]
This bug was reported in the  BI internal chat by Alex. C.

**Comment by trife** [comment]
I'm unable to replicate this on 5.6.16, so try updating. Also needs more information about what's being imported.

**Comment by PepperHouse** [comment]
@trife I imported an experiment from DeltaBreed via Brapi using Fieldbook 5.16.15.   I then added observation values to some of the entries and tried to export the file (database format) to my android device.  As soon as I  clicked Export, the app quit.   I was finally able to export the file using an older version of Fieldbook.

**Comment by trife** [comment]
Was this on a Galaxy Tab A? Can you post or email the system database export? Settings > Database > Export

**Comment by PepperHouse** [comment]
It was a pixel 7A.  I just updated to 5.6.16 and the export is working fine.  However, I still don't see the gridview button.

**Comment by trife** [comment]
Is it enabled? Settings > General > Datagrid

**Comment by PepperHouse** [comment]
This ticket can be closed.  Thank you!
