### ISSUE TITLE
BrAPI Integration: send token for all requests

### ISSUE THREAD

**Issue by nahuel-soldevilla** [PhenoApps/Field-Book#96]
BMS verifies authorization for every call, GET included. 
Right now I think Field book only sends the token for:

- PUT ImageContent
- PUT Observations
- PUT Image
- POST Image

cc @nickpalladino

**Comment by nickpalladino** [comment]
@trife, @nahuel-soldevilla is planning to do this fix and submit a pull request for it. The token should be included in all BrAPI calls.

**Comment by nahuel-soldevilla** [comment]
@BrapiCoordinatorSelby @mcrimi @jeback1

**Comment by abatac** [comment]
Hi everyone, I'm planning to create a PR to fix this issue. Can I have an access to the repository? 
@BrapiCoordinatorSelby @mcrimi @nahuel-soldevilla

**Comment by trife** [comment]
@abatac, I don't think you need write access to the repo to create a pull request.

**Comment by abatac** [comment]
@trife I tried to create a branch and push my changes but I'm getting this error:

```
Pushing to https://github.com/PhenoApps/Field-Book.git
remote: Permission to PhenoApps/Field-Book.git denied to abatac.
fatal: unable to access 'https://github.com/PhenoApps/Field-Book.git/': The requested URL returned error: 403
```

**Comment by trife** [comment]
You will need to fork the project into a personal repo, make the changes there, and then you can create a pull request back to the primary repo.
