### ISSUE TITLE
[BUG]: Date Observations not in BrAPI format

### ISSUE THREAD

**Issue by SCYarnes** [PhenoApps/Field-Book#964]
### Description

Export file from FB 
Expected Behavior: Date observations would be in BrAPI format 2024-05-02, like the time stamps
Actual Behavior: Date observations 5/2/24, unlike the time stamps
![image](https://github.com/PhenoApps/Field-Book/assets/142930813/a2c2aa32-97df-4314-8239-960b2333e853)

**Comment by trife** [comment]
Excel is changing the date formatting in your example.

![image](https://github.com/user-attachments/assets/0165a1d5-d303-4bb1-b6a0-e6a78095cecf)
