### ISSUE TITLE
Sort data grid plot numbers numerically[REQUEST]: 

### ISSUE THREAD

**Issue by krfritz** [PhenoApps/Field-Book#988]
### Description

When looking at data grid with plot numbers as row header sort 1 -> 2 -> 3 rather than 1 -> 10 -> 100

**Comment by chaneylc** [comment]
What version of FieldBook are you running, also please send us the import file you are using.

You can try to sort your field by "row" in the Fields page and this should work on the latest version.

**Comment by trife** [comment]
We can reopen this if provided with the file that is having issues.
