### ISSUE TITLE
[BUG]: Photo trait doesn't work if trait name contains "|" or ":"

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#998]
### Description

A trait name such as  "fruit plot harvest picture [photo]|UNH_01:0001025" won't save a photo unless the name is changed to exclude both the ":" and "|". Unfortunately, both of those characters are standard for trait imports from Breedbase due to the ontology format they use.

**Comment by trife** [comment]
This is fixed in #945 but we're working through a few other issues before merging. I'll leave the issue open for now.

**Comment by ch728** [comment]
I saw that this issue is fixed in 5.6; however, even though I have the trait format set to photo in breedbase 

![image](https://github.com/user-attachments/assets/9bbcaf23-7a74-46ba-bd10-2a0d133a0886)

It imports via brapi as a text trait.

![image](https://github.com/user-attachments/assets/af9f5bbf-fb5a-4e73-9872-6a3b5431705c)

There isn't a way to edit the trait type of an existing trait (which seems like a good idea) in version 5.6, so the trait can't be fixed after importing.

The brapi import works for categorical and numeric traits set in breedbase, but not for many of the other types of traits. I assume this is some kind of brapi  issue on the breedbase side of things.

**Comment by trife** [comment]
It's editable, when you go to the edit page you have to press back and select the different format. Making it slightly harder because in general, editing trait formats breaks a bunch of other things.
