### ISSUE TITLE
[BUG]: Photo trait export via Brapi to breedbase fails

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#999]
### Description

Not sure if this is due to the name being changed because of https://github.com/PhenoApps/Field-Book/issues/998 or a different issue. Other trait types export without error.

**Comment by ch728** [comment]
Interestingly if the photos are deleted (although as you can see they don't seem totally disappear) 
![20240712_162102_1439207639732081901](https://github.com/user-attachments/assets/3b8aac9b-861d-4dab-b558-e38824fafdf0)
Then the brapi export works (four entries at the bottom)
![image](https://github.com/user-attachments/assets/2fe5928e-8c4c-456c-a51d-4ff84400ef8d)

**Comment by trife** [comment]
Go ahead and reopen this if it's still happening, but closing for now with the release of v6 that should hopefully fix things. If this turns out to be an issue with naming, Breedbase will need to pull info out of the exif tags.
